// This file is automatically generated

#nullable enable

using RanseiLink.Core.Enums;
using RanseiLink.Core.Models;

namespace RanseiLink.Core.Services.ModelServices;


public partial interface IAbilityService : IModelService<Ability> {}

public partial class AbilityService : BaseDataModelService<Ability>, IAbilityService
{
    public static AbilityService Load(string dataFile) => new AbilityService(dataFile);
    private AbilityService(string dataFile) : base(dataFile, 0, 127, () => new Ability(), 128) {}

    public AbilityService(ModInfo mod) : this(Path.Combine(mod.FolderPath, Constants.AbilityRomPath)) {}

    public Ability Retrieve(AbilityId id) => Retrieve((int)id);

    public override string IdToName(int id)
    {
        return Retrieve(id).Name;
    }
}
