// This file is automatically generated

#nullable enable

using RanseiLink.Core.Enums;
using RanseiLink.Core.Models;

namespace RanseiLink.Core.Services.ModelServices;


public partial interface IBuildingService : IModelService<Building> {}

public partial class BuildingService : BaseDataModelService<Building>, IBuildingService
{
    private BuildingService(string dataFile, ConquestGameCode culture) : base(dataFile, 0, 118, () => new Building(culture), 119) {}

    public BuildingService(ModInfo mod) : this(Path.Combine(mod.FolderPath, Constants.BuildingRomPath), mod.GameCode) {}

    public Building Retrieve(BuildingId id) => Retrieve((int)id);

    public override string IdToName(int id)
    {
        return Retrieve(id).Name;
    }
}
