// This file is automatically generated

#nullable enable

using RanseiLink.Core.Enums;
using RanseiLink.Core.Models;

namespace RanseiLink.Core.Services.ModelServices;


public partial interface IGimmickService : IModelService<Gimmick> {}

public partial class GimmickService : BaseDataModelService<Gimmick>, IGimmickService
{
    public static GimmickService Load(string dataFile, ConquestGameCode culture) => new GimmickService(dataFile, culture);
    private GimmickService(string dataFile, ConquestGameCode culture) : base(dataFile, 0, 147, () => new Gimmick(culture)) {}

    public GimmickService(ModInfo mod) : this(Path.Combine(mod.FolderPath, Constants.GimmickRomPath), mod.GameCode) {}

    public Gimmick Retrieve(GimmickId id) => Retrieve((int)id);

    public override string IdToName(int id)
    {
        return Retrieve(id).Name;
    }
}
