// This file is automatically generated

#nullable enable

using RanseiLink.Core.Enums;
using RanseiLink.Core.Models;

namespace RanseiLink.Core.Services.ModelServices;


public partial interface IGimmickRangeService : IModelService<MoveRange> {}

public partial class GimmickRangeService : BaseDataModelService<MoveRange>, IGimmickRangeService
{
    public static GimmickRangeService Load(string dataFile) => new GimmickRangeService(dataFile);
    private GimmickRangeService(string dataFile) : base(dataFile, 0, 29, () => new MoveRange()) {}

    public GimmickRangeService(ModInfo mod) : this(Path.Combine(mod.FolderPath, Constants.GimmickRangeRomPath)) {}

    public MoveRange Retrieve(GimmickRangeId id) => Retrieve((int)id);

    public override string IdToName(int id)
    {
        return ((GimmickRangeId)id).ToString();
    }
}
