// This file is automatically generated

#nullable enable

using RanseiLink.Core.Enums;
using RanseiLink.Core.Models;

namespace RanseiLink.Core.Services.ModelServices;


public partial interface IGimmickObjectService : IModelService<GimmickObject> {}

public partial class GimmickObjectService : BaseDataModelService<GimmickObject>, IGimmickObjectService
{
    public static GimmickObjectService Load(string dataFile) => new GimmickObjectService(dataFile);
    private GimmickObjectService(string dataFile) : base(dataFile, 0, 99, () => new GimmickObject()) {}

    public GimmickObjectService(ModInfo mod) : this(Path.Combine(mod.FolderPath, Constants.GimmickObjectRomPath)) {}

    public GimmickObject Retrieve(GimmickObjectId id) => Retrieve((int)id);

    public override string IdToName(int id)
    {
        return ((GimmickObjectId)id).ToString();
    }
}
