// This file is automatically generated

#nullable enable

using RanseiLink.Core.Enums;
using RanseiLink.Core.Models;

namespace RanseiLink.Core.Services.ModelServices;


public partial interface IItemService : IModelService<Item> {}

public partial class ItemService : BaseDataModelService<Item>, IItemService
{
    public static ItemService Load(string dataFile) => new ItemService(dataFile);
    private ItemService(string dataFile) : base(dataFile, 0, 133, () => new Item(), 134) {}

    public ItemService(ModInfo mod) : this(Path.Combine(mod.FolderPath, Constants.ItemRomPath)) {}

    public Item Retrieve(ItemId id) => Retrieve((int)id);

    public override string IdToName(int id)
    {
        return Retrieve(id).Name;
    }
}
