// This file is automatically generated

#nullable enable

using RanseiLink.Core.Enums;
using RanseiLink.Core.Models;

namespace RanseiLink.Core.Services.ModelServices;


public partial interface IMapPointService : IModelService<MapPoint> {}

public partial class MapPointService : BaseDataModelService<MapPoint>, IMapPointService
{
    public static MapPointService Load(string dataFile) => new MapPointService(dataFile);
    private MapPointService(string dataFile) : base(dataFile, 0, 95, () => new MapPoint(), 96) {}

    public MapPointService(ModInfo mod) : this(Path.Combine(mod.FolderPath, Constants.MapPointRomPath)) {}

    public MapPoint Retrieve(MapPointId id) => Retrieve((int)id);

    public override string IdToName(int id)
    {
        return ((MapPointId)id).ToString();
    }
}
