// This file is automatically generated

#nullable enable

using RanseiLink.Core.Enums;
using RanseiLink.Core.Models;

namespace RanseiLink.Core.Services.ModelServices;


public partial interface IMaxLinkService : IModelService<MaxLink> {}

public partial class MaxLinkService : BaseDataModelService<MaxLink>, IMaxLinkService
{
    public static MaxLinkService Load(string dataFile) => new MaxLinkService(dataFile);
    private MaxLinkService(string dataFile) : base(dataFile, 0, 251, () => new MaxLink()) {}

    public MaxLinkService(ModInfo mod) : this(Path.Combine(mod.FolderPath, Constants.MaxLinkRomPath)) {}

    public MaxLink Retrieve(WarriorId id) => Retrieve((int)id);

    public override string IdToName(int id)
    {
        return ((WarriorId)id).ToString();
    }
}
