// This file is automatically generated

#nullable enable

using RanseiLink.Core.Enums;
using RanseiLink.Core.Models;

namespace RanseiLink.Core.Services.ModelServices;


public partial interface IMoveService : IModelService<Move> {}

public partial class MoveService : BaseDataModelService<Move>, IMoveService
{
    private MoveService(string dataFile) : base(dataFile, 0, 142, () => new Move()) {}

    public MoveService(ModInfo mod) : this(Path.Combine(mod.FolderPath, Constants.MoveRomPath)) {}

    public Move Retrieve(MoveId id) => Retrieve((int)id);

    public override string IdToName(int id)
    {
        return Retrieve(id).Name;
    }
}
