// This file is automatically generated

#nullable enable

using RanseiLink.Core.Enums;
using RanseiLink.Core.Models;

namespace RanseiLink.Core.Services.ModelServices;


public partial interface IMoveRangeService : IModelService<MoveRange> {}

public partial class MoveRangeService : BaseDataModelService<MoveRange>, IMoveRangeService
{
    public static MoveRangeService Load(string dataFile) => new MoveRangeService(dataFile);
    private MoveRangeService(string dataFile) : base(dataFile, 0, 29, () => new MoveRange()) {}

    public MoveRangeService(ModInfo mod) : this(Path.Combine(mod.FolderPath, Constants.MoveRangeRomPath)) {}

    public MoveRange Retrieve(MoveRangeId id) => Retrieve((int)id);

    public override string IdToName(int id)
    {
        return ((MoveRangeId)id).ToString();
    }
}
