// This file is automatically generated

#nullable enable

using RanseiLink.Core.Enums;
using RanseiLink.Core.Models;

namespace RanseiLink.Core.Services.ModelServices;


public partial interface IPokemonService : IModelService<Pokemon> {}

public partial class PokemonService : BaseDataModelService<Pokemon>, IPokemonService
{
    public static PokemonService Load(string dataFile) => new PokemonService(dataFile);
    private PokemonService(string dataFile) : base(dataFile, 0, 199, () => new Pokemon(), 511) {}

    public PokemonService(ModInfo mod) : this(Path.Combine(mod.FolderPath, Constants.PokemonRomPath)) {}

    public Pokemon Retrieve(PokemonId id) => Retrieve((int)id);

    public override string IdToName(int id)
    {
        return Retrieve(id).Name;
    }
}
