// This file is automatically generated

#nullable enable

using RanseiLink.Core.Enums;
using RanseiLink.Core.Models;

namespace RanseiLink.Core.Services.ModelServices;


public partial interface IWarriorSkillService : IModelService<WarriorSkill> {}

public partial class WarriorSkillService : BaseDataModelService<WarriorSkill>, IWarriorSkillService
{
    public static WarriorSkillService Load(string dataFile, ConquestGameCode culture) => new WarriorSkillService(dataFile, culture);
    private WarriorSkillService(string dataFile, ConquestGameCode culture) : base(dataFile, 0, 72, () => new WarriorSkill(culture)) {}

    public WarriorSkillService(ModInfo mod) : this(Path.Combine(mod.FolderPath, Constants.WarriorSkillRomPath), mod.GameCode) {}

    public WarriorSkill Retrieve(WarriorSkillId id) => Retrieve((int)id);

    public override string IdToName(int id)
    {
        return Retrieve(id).Name;
    }
}
