

namespace RanseiLink.Core.Enums
{

    [DefaultValues(NoAbility)]
    public enum AbilityId
    {
        NoAbility = 128,

        Levitate = 0,
        Mountaineer,
        WaveRider,
        Skater,
        Thrust,
        MoldBreaker,
        Turboblaze,
        Teravolt,
        Sniper,
        SolidRock,
        BattleArmor,
        ShellArmor,
        Sturdy,
        Unaware,
        ThickFat,
        Limber,
        Immunity,
        OwnTempo,
        InnerFocus,
        ClearBody,
        KeenEye,
        FlashFire,
        WaterAbsorb,
        VoltAbsorb,
        MotorDrive,
        Lightningrod,
        Perception,
        Parry,
        Instinct,
        Dodge,
        JaggedEdge,
        PoisonPoint,
        Static,
        FlameBody,
        Frostbite,
        Tenacity,
        Blaze,
        Torrent,
        Overgrow,
        Swarm,
        Guts,
        Pride,
        Steadfast, // dummy0
        Justified,
        DeepSleep,
        PowerNap,
        Spirit,
        WarmBlanket,
        Gulp,
        Herbivore,
        Sandpit,
        HotBlooded,
        Medic,
        LifeForce,
        Lunchbox,
        ShedSkin,
        Healer,
        Nurse,
        Melee,
        Sponge,
        Bodyguard,
        Hero,
        LastBastion,
        NoGuard, // dummy1
        Stealth,
        Vanguard,
        Nomad,
        Sequence,
        GrassCloak,
        Compoundeyes,
        Simple,
        Moxie,
        Celebrate,
        Lullaby,
        Calming,
        Daze,
        Intimidate,
        Frighten,
        Interference,
        MoodMaker,
        Confidence,
        Fortune,
        Bonanza,
        Explode,
        Illusion,
        Omnipotent,
        Share,
        BlackHole,
        dummy2, // Enables a Pokémon to chop down trees with their attacks.
        dummy3, // Enables a Pokémon to smash rocks with their attacks.
        ShadowDash,
        Sprint,
        Disgust,
        HighRise,
        Climber,
        FlameBoost,
        AquaBoost,
        RunUp,
        Conqueror,
        Shackle,
        Decoy,
        Shield,
        dummy4, // The Pokémon can move freely through squares that contain allies.
        dummy5, // The Pokémon can restore a used Warrior Skill when their army is struggling.
        dummy6, // Improves stats when surrounded by enemies.
        dummy7, // Adjacent enemies can move only one square.
        dummy8, // There's no room for this move to have a description
        dummy9,
        dummy10,
        dummy11,
        dummy12,
        dummy13,
        dummy14,
        dummy15,
        dummy16,
        dummy17,
        dummy18,
        dummy19,
        dummy20,
        dummy21,
        dummy22,
        dummy23,
        dummy24,
        dummy25,
        dummy26,
        dummy27,
        dummy28,
        dummy29,
    }
}