
namespace RanseiLink.Core.Enums
{

    [DefaultValues(Default)]
    public enum BattleConfigId
    {
        Aurora,
        Ignis,
        Fontaine,
        Violight,
        Greenleaf,
        Nixtorm,
        Pugilis,
        Viperia,
        Terrera,
        Avia,
        Illusio,
        Chrysalia,
        Cragspur,
        Spectra,
        Dragnor,
        Yakasha,
        Valora,
        InfiniteTower,
        TestMap_1,
        TestMap_2,
        SacredRuins,
        TestMap_3,
        TestMap_4,
        Ravine_3,
        Ravine_2,
        Ravine_1,
        Cave_3,
        Cave_2,
        Cave_1,
        FloatingRock_3,
        FloatingRock_2,
        FloatingRock_1,
        Farm_3,
        Farm_2,
        Farm_1,
        SkyGarden_3,
        SkyGarden_2,
        SkyGarden_1,
        SnowyMountain_3,
        SnowyMountain_2,
        SnowyMountain_1,
        Park_3,
        Park_2,
        Park_1,
        TestMap_5,
        TestMap_6,
        TestMap_7,
        Default // anything this higher gives the black screen of death followed by a corrupt battle screen softlock
    }
}