
namespace RanseiLink.Core.Enums;

public enum BattleMapId : uint
{
    Aurora,
    Ignis,
    Fontaine,
    Violight,
    Greenleaf,
    Nixtorm,
    Pugilis,
    Viperia,
    Terrera,
    Avia,
    Illusio,
    Chrysalia,
    Cragspur,
    Spectra,
    Dragnor,
    Yakasha,
    Valora,
    FinalBattle,
    Unknown_18,
    Unknown_19,
    Unknown_20,
    Unknown_21,
    Unknown_22,
    Unknown_23,
    Unknown_24,
    Unknown_25,
    Unknown_26,
    Unknown_27,
    Unknown_28,
    Unknown_29,
    Unknown_30,
    Unknown_31,
    Unknown_32,
    Unknown_33,
    Unknown_34,
    Unknown_35,
    Unknown_36,
    Unknown_37,
    Unknown_38,
    Unknown_39,
    Unknown_40,
    Unknown_41,
    Unknown_42,
    Unknown_43,
    Unknown_44,
    Unknown_45,
    Unknown_46,
    // anything higher gives the black screen of death followed by a corrupt battle screen softlock
}
