namespace RanseiLink.Core.Enums;


public enum GimmickRangeId
{
    NoRange,
    DiamondAdjacent,
    SquareVertices,
    Right1Tile,
    Behind1Tile,
    Column2TilesRight,
    Column2TilesBack,
    RightBackCorner,
    AheadAndBehind,
    RightAndLeft,
    RingAdjacent,
    LargeCrossAdjacent,
    Ahead1Tile,
    Column2TilesAhead,
    Unused_1,
    Ahead2Tiles,
    Column3TilesAhead,
    RectangleBackAdjacent,
    Left1Tile,
    Square,
    Cross,
    LargeRingAdjacent,
    LargeDiamond,
    RowAhead,
    Unused_2,
    Unused_3,
    Unused_4,
    Unused_5,
    Unused_6,
    Unused_7,
}