
namespace RanseiLink.Core.Enums;


[DefaultValues(Default)]
public enum GimmickObjectId
{
    Banner_WithPokeball,
    Tree, // normal
    SnowyTree, // snow
    DeadTree,
    Rock,
    Switch_State1,
    Hole_Black, // black hole
    Scarecrow,
    Trap, // dirt hole
    PillarOfFire_Ignited,
    HotSpring,
    Fountain,
    Emerald,
    BlossomTree,
    GreenGrass,
    StrangeFlower,
    Icicle,
    FightBell,
    AnthuriumFlower,
    WaterBucket_0,
    Doll,
    GrassyPond,
    FruitTree,
    WhiteCube,
    BlueCarpet,
    PokemariBall,
    PurpleCrystal,
    Statue,
    Node,
    MysteryBox,
    Camera,
    SpiralFence_0,
    Crane,
    Banner_WithoutPokeball, // without pokeball
    PalmTree,
    FallenPillar,
    BrokenRuins,
    Log_0,
    TreasureBox_Purple,
    TreasureBox_BlackGold,
    RedArrow,
    BlueCrescent,
    Ice,
    PillarOfFire_Extinguished,
    FriedEgg,
    PurpleFriedEgg,
    PurpleSpiderWeb,
    Warp,
    Fireball_Blue,
    Fireball_Magenta,
    NoModel_0,
    YellowGrass,
    LimeGrass,
    BlueGrass,
    DarkGreenGrass,
    ElectricSwitch_Red, // red/pink
    ElectricSwitch_Yellow, // yellow/gold
    ElectricSwitch_Purple, // purple
    ElectricSwitch_Blue, // blue
    SpiralFence_1,
    NoModel_1,
    NoModel_2,
    NoModel_3,
    NoModel_4,
    NoModel_5,
    NoModel_6,
    NoModel_7,
    NoModel_8,
    NoModel_9,
    NoModel_10,
    WaterWheel,
    FloodGate,
    Vine,
    RopeBridge,
    FenceTrap,
    WaterFeature,
    StoneDoor,
    Boulder,
    CogWheel,
    Hole,
    RainbowToppedPlatform,
    ThinIce,
    DriftingIce,
    FloatingCube,
    Screen,
    Lift,
    BrokenPillar,
    RuinsPile,
    Log,
    SecretPassage,
    JumpRamp,
    HotSpring_Full,
    HotSpring_Empty,
    SurpriseBox,
    WaterBucket_Full,
    WaterBucket_Empty,
    Oasis_Full,
    Oasis_Empty,
    NoModel_11,
    NoModel_12,
    Default
}