// This file is automatically generated

#nullable enable

using RanseiLink.Core.Enums;
using RanseiLink.Core.Services.ModelServices;

namespace RanseiLink.Console.ModelCommands;

[Command("episode", Description = "Get data on a given Episode.")]
public class EpisodeCommand(ICurrentModService currentModService) : ICommand
{
    [CommandParameter(0, Description = "Episode ID.", Name = "id")]
    public EpisodeId Id { get; set; }

    public ValueTask ExecuteAsync(IConsole console)
    {
        if (!currentModService.TryGetCurrentModServiceGetter(out var services))
        {
            console.Output.WriteLine("No mod selected");
            return default;
        }

        var service = services.Get<IEpisodeService>();

        var model = service.Retrieve((int)Id);

        console.Render(model, Id);

        return default;
    }
}
