// This file is automatically generated

#nullable enable

using RanseiLink.Core.Enums;
using RanseiLink.Core.Services.ModelServices;

namespace RanseiLink.Console.ModelCommands;

[Command("mappoint", Description = "Get data on a given MapPoint.")]
public class MapPointCommand(ICurrentModService currentModService) : ICommand
{
    [CommandParameter(0, Description = "MapPoint ID.", Name = "id")]
    public MapPointId Id { get; set; }

    public ValueTask ExecuteAsync(IConsole console)
    {
        if (!currentModService.TryGetCurrentModServiceGetter(out var services))
        {
            console.WriteLine("No mod selected");
            return default;
        }

        var service = services.Get<IMapPointService>();

        var model = service.Retrieve((int)Id);

        console.Render(model, Id);

        return default;
    }
}
