// This file is automatically generated

#nullable enable

using RanseiLink.Core.Enums;
using RanseiLink.Core.Services.ModelServices;

namespace RanseiLink.Console.ModelCommands;

[Command("warriorskill", Description = "Get data on a given WarriorSkill.")]
public class WarriorSkillCommand(ICurrentModService currentModService) : ICommand
{
    [CommandParameter(0, Description = "WarriorSkill ID.", Name = "id")]
    public WarriorSkillId Id { get; set; }

    public ValueTask ExecuteAsync(IConsole console)
    {
        if (!currentModService.TryGetCurrentModServiceGetter(out var services))
        {
            console.WriteLine("No mod selected");
            return default;
        }

        var service = services.Get<IWarriorSkillService>();

        var model = service.Retrieve((int)Id);

        console.Render(model, Id);

        return default;
    }
}
