// This file is automatically generated

#nullable enable

using RanseiLink.Core.Enums;
using RanseiLink.Core.Graphics;
using RanseiLink.Core.Models;

namespace RanseiLink.Console;

public static partial class RenderExtensions
{
    public static void Render(this IConsole console, EventSpeaker model, EventSpeakerId id)
    {
        console.WriteTitle(id.ToString());
        console.WriteProperty("Name", model.Name);
        console.WriteProperty("Sprite", model.Sprite);
    }
}
