// This file is automatically generated

#nullable enable

using RanseiLink.Core.Enums;
using RanseiLink.Core.Graphics;
using RanseiLink.Core.Models;

namespace RanseiLink.Console;

public static partial class RenderExtensions
{
    public static void Render(this IConsole console, Ability model, object title)
    {
        console.WriteTitle(title);
        console.WriteProperty("Name", model.Name);
        console.WriteProperty("Effect1Amount", model.Effect1Amount);
        console.WriteProperty("Effect1", model.Effect1);
        console.WriteProperty("Effect2", model.Effect2);
        console.WriteProperty("Effect2Amount", model.Effect2Amount);
    }
    public static void Render(this IConsole console, BaseWarrior model, object title)
    {
        console.WriteTitle(title);
        console.WriteProperty("Sprite", model.Sprite);
        console.WriteProperty("SpeakerId", model.SpeakerId);
        console.WriteProperty("Gender", model.Gender);
        console.WriteProperty("Name", model.Name);
        console.WriteProperty("Speciality1", model.Speciality1);
        console.WriteProperty("Speciality2", model.Speciality2);
        console.WriteProperty("Weakness1", model.Weakness1);
        console.WriteProperty("Weakness2", model.Weakness2);
        console.WriteProperty("Skill", model.Skill);
        console.WriteProperty("Power", model.Power);
        console.WriteProperty("Wisdom", model.Wisdom);
        console.WriteProperty("Charisma", model.Charisma);
        console.WriteProperty("Capacity", model.Capacity);
        console.WriteProperty("RankUpCondition1", model.RankUpCondition1);
        console.WriteProperty("RankUpCondition2", model.RankUpCondition2);
        console.WriteProperty("Quantity1ForRankUpCondition", model.Quantity1ForRankUpCondition);
        console.WriteProperty("Quantity2ForRankUpCondition", model.Quantity2ForRankUpCondition);
        console.WriteProperty("RankUp", model.RankUp);
        console.WriteProperty("RankUpPokemon1", model.RankUpPokemon1);
        console.WriteProperty("RankUpPokemon2", model.RankUpPokemon2);
        console.WriteProperty("RankUpLink", model.RankUpLink);
    }
    public static void Render(this IConsole console, BattleConfig model, object title)
    {
        console.WriteTitle(title);
        console.WriteProperty("Map", model.Map);
        console.WriteProperty("MapVariant", model.MapVariant);
        console.WriteProperty("Minimap", model.Minimap);
        console.WriteProperty("MinimapVariant", model.MinimapVariant);
        console.WriteProperty("Unknown", model.Unknown);
        console.WriteProperty("UpperAtmosphereColor", model.UpperAtmosphereColor);
        console.WriteProperty("MiddleAtmosphereColor", model.MiddleAtmosphereColor);
        console.WriteProperty("LowerAtmosphereColor", model.LowerAtmosphereColor);
        console.WriteProperty("VictoryCondition", model.VictoryCondition);
        console.WriteProperty("DefeatCondition", model.DefeatCondition);
        console.WriteProperty("NumberOfTurns", model.NumberOfTurns);
        console.WriteProperty("Treasure1", model.Treasure1);
        console.WriteProperty("Treasure2", model.Treasure2);
        console.WriteProperty("Treasure3", model.Treasure3);
        console.WriteProperty("Treasure4", model.Treasure4);
        console.WriteProperty("Treasure5", model.Treasure5);
        console.WriteProperty("Treasure6", model.Treasure6);
        console.WriteProperty("Treasure7", model.Treasure7);
        console.WriteProperty("Treasure8", model.Treasure8);
        console.WriteProperty("Treasure9", model.Treasure9);
        console.WriteProperty("Treasure10", model.Treasure10);
        console.WriteProperty("Treasure11", model.Treasure11);
        console.WriteProperty("Treasure12", model.Treasure12);
    }
    public static void Render(this IConsole console, Building model, object title)
    {
        console.WriteTitle(title);
        console.WriteProperty("Name", model.Name);
        console.WriteProperty("Building1", model.Building1);
        console.WriteProperty("Building2", model.Building2);
        console.WriteProperty("Building3", model.Building3);
        console.WriteProperty("Building4", model.Building4);
        console.WriteProperty("Building5", model.Building5);
        console.WriteProperty("Building6", model.Building6);
        console.WriteProperty("Building7", model.Building7);
        console.WriteProperty("Building8", model.Building8);
        console.WriteProperty("Kingdom", model.Kingdom);
        console.WriteProperty("BattleConfig1", model.BattleConfig1);
        console.WriteProperty("BattleConfig2", model.BattleConfig2);
        console.WriteProperty("BattleConfig3", model.BattleConfig3);
        console.WriteProperty("Sprite1", model.Sprite1);
        console.WriteProperty("Sprite2", model.Sprite2);
        console.WriteProperty("Sprite3", model.Sprite3);
        console.WriteProperty("Function", model.Function);
    }
    public static void Render(this IConsole console, Episode model, object title)
    {
        console.WriteTitle(title);
        console.WriteProperty("Order", model.Order);
        console.WriteProperty("Scenario", model.Scenario);
        console.WriteProperty("UnlockCondition", model.UnlockCondition);
        console.WriteProperty("Difficulty", model.Difficulty);
        console.WriteProperty("ClearCondition", model.ClearCondition);
    }
    public static void Render(this IConsole console, EventSpeaker model, object title)
    {
        console.WriteTitle(title);
        console.WriteProperty("Name", model.Name);
        console.WriteProperty("Sprite", model.Sprite);
    }
    public static void Render(this IConsole console, Gimmick model, object title)
    {
        console.WriteTitle(title);
        console.WriteProperty("Name", model.Name);
        console.WriteProperty("Image", model.Image);
        console.WriteProperty("AttackType", model.AttackType);
        console.WriteProperty("DestroyType", model.DestroyType);
        console.WriteProperty("State1Sprite", model.State1Sprite);
        console.WriteProperty("State2Sprite", model.State2Sprite);
        console.WriteProperty("Effect", model.Effect);
        console.WriteProperty("UnknownQuantity1", model.UnknownQuantity1);
        console.WriteProperty("Animation1", model.Animation1);
        console.WriteProperty("Animation2", model.Animation2);
        console.WriteProperty("Range", model.Range);
    }
    public static void Render(this IConsole console, Item model, object title)
    {
        console.WriteTitle(title);
        console.WriteProperty("Name", model.Name);
        console.WriteProperty("PurchaseMethod", model.PurchaseMethod);
        console.WriteProperty("Category", model.Category);
        console.WriteProperty("Effect", model.Effect);
        console.WriteProperty("EffectDuration", model.EffectDuration);
        console.WriteProperty("CraftingIngredient1", model.CraftingIngredient1);
        console.WriteProperty("CraftingIngredient1Amount", model.CraftingIngredient1Amount);
        console.WriteProperty("CraftingIngredient2", model.CraftingIngredient2);
        console.WriteProperty("CraftingIngredient2Amount", model.CraftingIngredient2Amount);
        console.WriteProperty("UnknownItem", model.UnknownItem);
        console.WriteProperty("ShopPriceMultiplier", model.ShopPriceMultiplier);
        console.WriteProperty("QuantityForEffect", model.QuantityForEffect);
    }
    public static void Render(this IConsole console, Kingdom model, object title)
    {
        console.WriteTitle(title);
        console.WriteProperty("Name", model.Name);
        console.WriteProperty("Unknown1", model.Unknown1);
        console.WriteProperty("MapConnection0", model.MapConnection0);
        console.WriteProperty("MapConnection1", model.MapConnection1);
        console.WriteProperty("MapConnection2", model.MapConnection2);
        console.WriteProperty("MapConnection3", model.MapConnection3);
        console.WriteProperty("MapConnection4", model.MapConnection4);
        console.WriteProperty("MapConnection5", model.MapConnection5);
        console.WriteProperty("MapConnection6", model.MapConnection6);
        console.WriteProperty("MapConnection7", model.MapConnection7);
        console.WriteProperty("MapConnection8", model.MapConnection8);
        console.WriteProperty("MapConnection9", model.MapConnection9);
        console.WriteProperty("MapConnection10", model.MapConnection10);
        console.WriteProperty("MapConnection11", model.MapConnection11);
        console.WriteProperty("MapConnection12", model.MapConnection12);
        console.WriteProperty("BattleConfig", model.BattleConfig);
        console.WriteProperty("Unknown2", model.Unknown2);
        console.WriteProperty("Unknown3", model.Unknown3);
    }
    public static void Render(this IConsole console, Move model, object title)
    {
        console.WriteTitle(title);
        console.WriteProperty("Name", model.Name);
        console.WriteProperty("MovementFlags", model.MovementFlags);
        console.WriteProperty("Type", model.Type);
        console.WriteProperty("Power", model.Power);
        console.WriteProperty("Effect1", model.Effect1);
        console.WriteProperty("Effect1Chance", model.Effect1Chance);
        console.WriteProperty("Range", model.Range);
        console.WriteProperty("Effect2", model.Effect2);
        console.WriteProperty("Effect2Chance", model.Effect2Chance);
        console.WriteProperty("Effect3", model.Effect3);
        console.WriteProperty("Effect3Chance", model.Effect3Chance);
        console.WriteProperty("Effect4", model.Effect4);
        console.WriteProperty("Effect4Chance", model.Effect4Chance);
        console.WriteProperty("Accuracy", model.Accuracy);
        console.WriteProperty("StartupAnimation", model.StartupAnimation);
        console.WriteProperty("ProjectileAnimation", model.ProjectileAnimation);
        console.WriteProperty("ImpactAnimation", model.ImpactAnimation);
        console.WriteProperty("AdditionalAnimation", model.AdditionalAnimation);
        console.WriteProperty("UnknownOption", model.UnknownOption);
        console.WriteProperty("Movement", model.Movement);
        console.WriteProperty("MovementAnimation", model.MovementAnimation);
        console.WriteProperty("UnknownValue_6_28_4", model.UnknownValue_6_28_4);
    }
    public static void Render(this IConsole console, Pokemon model, object title)
    {
        console.WriteTitle(title);
        console.WriteProperty("Name", model.Name);
        console.WriteProperty("Hp", model.Hp);
        console.WriteProperty("EvolutionCondition1", model.EvolutionCondition1);
        console.WriteProperty("EvolutionCondition2", model.EvolutionCondition2);
        console.WriteProperty("IdleMotion", model.IdleMotion);
        console.WriteProperty("Atk", model.Atk);
        console.WriteProperty("Def", model.Def);
        console.WriteProperty("Spe", model.Spe);
        console.WriteProperty("IsLegendary", model.IsLegendary);
        console.WriteProperty("AsymmetricBattleSprite", model.AsymmetricBattleSprite);
        console.WriteProperty("LongAttackAnimation", model.LongAttackAnimation);
        console.WriteProperty("Type1", model.Type1);
        console.WriteProperty("Type2", model.Type2);
        console.WriteProperty("Move", model.Move);
        console.WriteProperty("Ability1", model.Ability1);
        console.WriteProperty("Ability2", model.Ability2);
        console.WriteProperty("Ability3", model.Ability3);
        console.WriteProperty("QuantityForEvolutionCondition1", model.QuantityForEvolutionCondition1);
        console.WriteProperty("QuantityForEvolutionCondition2", model.QuantityForEvolutionCondition2);
        console.WriteProperty("MovementRange", model.MovementRange);
        console.WriteProperty("MinEvolutionTableEntry", model.MinEvolutionTableEntry);
        console.WriteProperty("MaxEvolutionTableEntry", model.MaxEvolutionTableEntry);
        console.WriteProperty("NationalPokedexNumber", model.NationalPokedexNumber);
        console.WriteProperty("NameOrderIndex", model.NameOrderIndex);
        console.WriteProperty("CatchRate", model.CatchRate);
        console.WriteProperty("UnknownAnimationValue", model.UnknownAnimationValue);
        console.WriteProperty("BattleIntroSpriteOffset", model.BattleIntroSpriteOffset);
        console.WriteProperty("Weight", model.Weight);
    }
    public static void Render(this IConsole console, WarriorSkill model, object title)
    {
        console.WriteTitle(title);
        console.WriteProperty("Name", model.Name);
        console.WriteProperty("Effect1Amount", model.Effect1Amount);
        console.WriteProperty("Effect1", model.Effect1);
        console.WriteProperty("Effect2", model.Effect2);
        console.WriteProperty("Effect2Amount", model.Effect2Amount);
        console.WriteProperty("Effect3", model.Effect3);
        console.WriteProperty("Duration", model.Duration);
        console.WriteProperty("Effect3Amount", model.Effect3Amount);
        console.WriteProperty("Target", model.Target);
        console.WriteProperty("Animation", model.Animation);
    }
}
