// This file is automatically generated

#nullable enable

using RanseiLink.Core.Services.ModelServices;

namespace RanseiLink.Core.Services;

public partial interface IModServiceContainer
{
    public IAbilityService Ability { get; }
    public IBaseWarriorService BaseWarrior { get; }
    public IBattleConfigService BattleConfig { get; }
    public IBuildingService Building { get; }
    public IEpisodeService Episode { get; }
    public IEventSpeakerService EventSpeaker { get; }
    public IGimmickService Gimmick { get; }
    public IGimmickObjectService GimmickObject { get; }
    public IItemService Item { get; }
    public IKingdomService Kingdom { get; }
    public IMapPointService MapPoint { get; }
    public IMaxLinkService MaxLink { get; }
    public IMoveService Move { get; }
    public IMoveAnimationService MoveAnimation { get; }
    public IMoveRangeService MoveRange { get; }
    public IGimmickRangeService GimmickRange { get; }
    public IPokemonService Pokemon { get; }
    public IWarriorSkillService WarriorSkill { get; }
}
