// This file is automatically generated

#nullable enable

using RanseiLink.Core.Enums;
using RanseiLink.Core.Graphics;

namespace RanseiLink.Core.Models;

public partial class Ability : BaseDataWindow, INamedModel
{
    public event EventHandler? NameChanged;
    public const int DataLength = 0x14;
    public Ability(byte[] data) : base(data, DataLength) { }
    public Ability() : this(new byte[DataLength]) { }

    public int Name_MaxLength
    {
        get => 14;
    }
    public string Name
    {
        get => GetPaddedUtf8String(0, Name_MaxLength);
        set
        {
            SetPaddedUtf8String(0, Name_MaxLength, value);
            NameChanged?.Invoke(this, EventArgs.Empty);
        }
    }

    public int Effect1_Quantity
    {
        get => GetInt(3, 24, 8);
        set => SetInt(3, 24, 8, value);
    }

    public AbilityEffectId Effect1
    {
        get => (AbilityEffectId)GetInt(4, 0, 5);
        set => SetInt(4, 0, 5, (int)value);
    }

    public AbilityEffectId Effect2
    {
        get => (AbilityEffectId)GetInt(4, 5, 5);
        set => SetInt(4, 5, 5, (int)value);
    }

    public int Effect2_Quantity
    {
        get => GetInt(4, 10, 8);
        set => SetInt(4, 10, 8, value);
    }
}