// This file is automatically generated

#nullable enable

using RanseiLink.Core.Enums;
using RanseiLink.Core.Graphics;

namespace RanseiLink.Core.Models;

public partial class BattleConfig : BaseDataWindow
{
    public const int DataLength = 0x18;
    public BattleConfig(byte[] data) : base(data, DataLength) { }
    public BattleConfig() : this(new byte[DataLength]) { }

    public int Map
    {
        get => GetInt(0, 0, 6);
        set => SetInt(0, 0, 6, value);
    }

    public int MapVariant
    {
        get => GetInt(0, 6, 5);
        set => SetInt(0, 6, 5, value);
    }

    public int Minimap
    {
        get => GetInt(2, 13, 5);
        set => SetInt(2, 13, 5, value);
    }

    public int MinimapVariant
    {
        get => GetInt(2, 10, 3);
        set => SetInt(2, 10, 3, value);
    }

    public int Unknown
    {
        get => GetInt(2, 19, 5);
        set => SetInt(2, 19, 5, value);
    }

    public Rgb15 UpperAtmosphereColor
    {
        get => (Rgb15)GetInt(0, 11, 15);
        set => SetInt(0, 11, 15, (int)value);
    }

    public Rgb15 MiddleAtmosphereColor
    {
        get => (Rgb15)GetInt(1, 0, 15);
        set => SetInt(1, 0, 15, (int)value);
    }

    public Rgb15 LowerAtmosphereColor
    {
        get => (Rgb15)GetInt(1, 15, 15);
        set => SetInt(1, 15, 15, (int)value);
    }

    public BattleVictoryConditionFlags VictoryCondition
    {
        get => (BattleVictoryConditionFlags)GetInt(2, 0, 5);
        set => SetInt(2, 0, 5, (int)value);
    }

    public BattleVictoryConditionFlags DefeatCondition
    {
        get => (BattleVictoryConditionFlags)GetInt(2, 5, 5);
        set => SetInt(2, 5, 5, (int)value);
    }

    public int NumberOfTurns
    {
        get => GetInt(2, 24, 5);
        set => SetInt(2, 24, 5, value);
    }

    public ItemId Treasure1
    {
        get => (ItemId)GetByte(12);
        set => SetByte(12, (byte)value);
    }

    public ItemId Treasure2
    {
        get => (ItemId)GetByte(13);
        set => SetByte(13, (byte)value);
    }

    public ItemId Treasure3
    {
        get => (ItemId)GetByte(14);
        set => SetByte(14, (byte)value);
    }

    public ItemId Treasure4
    {
        get => (ItemId)GetByte(15);
        set => SetByte(15, (byte)value);
    }

    public ItemId Treasure5
    {
        get => (ItemId)GetByte(16);
        set => SetByte(16, (byte)value);
    }

    public ItemId Treasure6
    {
        get => (ItemId)GetByte(17);
        set => SetByte(17, (byte)value);
    }

    public ItemId Treasure7
    {
        get => (ItemId)GetByte(18);
        set => SetByte(18, (byte)value);
    }

    public ItemId Treasure8
    {
        get => (ItemId)GetByte(19);
        set => SetByte(19, (byte)value);
    }

    public ItemId Treasure9
    {
        get => (ItemId)GetByte(20);
        set => SetByte(20, (byte)value);
    }

    public ItemId Treasure10
    {
        get => (ItemId)GetByte(21);
        set => SetByte(21, (byte)value);
    }

    public ItemId Treasure11
    {
        get => (ItemId)GetByte(22);
        set => SetByte(22, (byte)value);
    }

    public ItemId Treasure12
    {
        get => (ItemId)GetByte(23);
        set => SetByte(23, (byte)value);
    }
}