// This file is automatically generated

#nullable enable

using RanseiLink.Core.Enums;
using RanseiLink.Core.Graphics;

namespace RanseiLink.Core.Models;

public partial class Building : BaseDataWindow, INamedModel
{
    public event EventHandler? NameChanged;
    private ConquestGameCode _culture;
    public static int DataLength(ConquestGameCode culture)
    {
        return culture switch
        {
            ConquestGameCode.VPYJ => 0x20,
            _ => 0x24
        };
    }
    public Building(byte[] data, ConquestGameCode culture) : base(data, DataLength(culture)) { _culture = culture; }
    public Building(ConquestGameCode culture) : this(new byte[DataLength(culture)], culture) { }

    public int Name_MaxLength
    {
        get
        {
            if (_culture == ConquestGameCode.VPYJ)
            {
                return 16;
            }
            else
            {
                return 18;
            }
        }
    }
    public string Name
    {
        get => GetPaddedUtf8String(0, Name_MaxLength);
        set
        {
            SetPaddedUtf8String(0, Name_MaxLength, value);
            NameChanged?.Invoke(this, EventArgs.Empty);
        }
    }

    public BuildingId Building1
    {
        get
        {
            if (_culture == ConquestGameCode.VPYJ)
            {
                return (BuildingId)GetByte(17);
            }
            else
            {
                return (BuildingId)GetByte(19);
            }
        }
        set
        {
            if (_culture == ConquestGameCode.VPYJ)
            {
                SetByte(17, (byte)value);
            }
            else
            {
                SetByte(19, (byte)value);
            }
        }
    }

    public BuildingId Building2
    {
        get
        {
            if (_culture == ConquestGameCode.VPYJ)
            {
                return (BuildingId)GetByte(18);
            }
            else
            {
                return (BuildingId)GetByte(20);
            }
        }
        set
        {
            if (_culture == ConquestGameCode.VPYJ)
            {
                SetByte(18, (byte)value);
            }
            else
            {
                SetByte(20, (byte)value);
            }
        }
    }

    public BuildingId Building3
    {
        get
        {
            if (_culture == ConquestGameCode.VPYJ)
            {
                return (BuildingId)GetByte(19);
            }
            else
            {
                return (BuildingId)GetByte(21);
            }
        }
        set
        {
            if (_culture == ConquestGameCode.VPYJ)
            {
                SetByte(19, (byte)value);
            }
            else
            {
                SetByte(21, (byte)value);
            }
        }
    }

    public BuildingId Building4
    {
        get
        {
            if (_culture == ConquestGameCode.VPYJ)
            {
                return (BuildingId)GetByte(20);
            }
            else
            {
                return (BuildingId)GetByte(22);
            }
        }
        set
        {
            if (_culture == ConquestGameCode.VPYJ)
            {
                SetByte(20, (byte)value);
            }
            else
            {
                SetByte(22, (byte)value);
            }
        }
    }

    public BuildingId Building5
    {
        get
        {
            if (_culture == ConquestGameCode.VPYJ)
            {
                return (BuildingId)GetByte(21);
            }
            else
            {
                return (BuildingId)GetByte(23);
            }
        }
        set
        {
            if (_culture == ConquestGameCode.VPYJ)
            {
                SetByte(21, (byte)value);
            }
            else
            {
                SetByte(23, (byte)value);
            }
        }
    }

    public BuildingId Building6
    {
        get
        {
            if (_culture == ConquestGameCode.VPYJ)
            {
                return (BuildingId)GetByte(22);
            }
            else
            {
                return (BuildingId)GetByte(24);
            }
        }
        set
        {
            if (_culture == ConquestGameCode.VPYJ)
            {
                SetByte(22, (byte)value);
            }
            else
            {
                SetByte(24, (byte)value);
            }
        }
    }

    public BuildingId Building7
    {
        get
        {
            if (_culture == ConquestGameCode.VPYJ)
            {
                return (BuildingId)GetByte(23);
            }
            else
            {
                return (BuildingId)GetByte(25);
            }
        }
        set
        {
            if (_culture == ConquestGameCode.VPYJ)
            {
                SetByte(23, (byte)value);
            }
            else
            {
                SetByte(25, (byte)value);
            }
        }
    }

    public BuildingId Building8
    {
        get
        {
            if (_culture == ConquestGameCode.VPYJ)
            {
                return (BuildingId)GetByte(24);
            }
            else
            {
                return (BuildingId)GetByte(26);
            }
        }
        set
        {
            if (_culture == ConquestGameCode.VPYJ)
            {
                SetByte(24, (byte)value);
            }
            else
            {
                SetByte(26, (byte)value);
            }
        }
    }

    public KingdomId Kingdom
    {
        get
        {
            if (_culture == ConquestGameCode.VPYJ)
            {
                return (KingdomId)GetInt(6, 8, 5);
            }
            else
            {
                return (KingdomId)GetInt(6, 24, 5);
            }
        }
        set
        {
            if (_culture == ConquestGameCode.VPYJ)
            {
                SetInt(6, 8, 5, (int)value);
            }
            else
            {
                SetInt(6, 24, 5, (int)value);
            }
        }
    }

    public BattleConfigId BattleConfig1
    {
        get
        {
            if (_culture == ConquestGameCode.VPYJ)
            {
                return (BattleConfigId)GetInt(6, 16, 7);
            }
            else
            {
                return (BattleConfigId)GetInt(7, 0, 7);
            }
        }
        set
        {
            if (_culture == ConquestGameCode.VPYJ)
            {
                SetInt(6, 16, 7, (int)value);
            }
            else
            {
                SetInt(7, 0, 7, (int)value);
            }
        }
    }

    public BattleConfigId BattleConfig2
    {
        get
        {
            if (_culture == ConquestGameCode.VPYJ)
            {
                return (BattleConfigId)GetInt(6, 23, 7);
            }
            else
            {
                return (BattleConfigId)GetInt(7, 7, 7);
            }
        }
        set
        {
            if (_culture == ConquestGameCode.VPYJ)
            {
                SetInt(6, 23, 7, (int)value);
            }
            else
            {
                SetInt(7, 7, 7, (int)value);
            }
        }
    }

    public BattleConfigId BattleConfig3
    {
        get
        {
            if (_culture == ConquestGameCode.VPYJ)
            {
                return (BattleConfigId)GetInt(7, 0, 7);
            }
            else
            {
                return (BattleConfigId)GetInt(8, 0, 7);
            }
        }
        set
        {
            if (_culture == ConquestGameCode.VPYJ)
            {
                SetInt(7, 0, 7, (int)value);
            }
            else
            {
                SetInt(8, 0, 7, (int)value);
            }
        }
    }

    public int Sprite1
    {
        get
        {
            if (_culture == ConquestGameCode.VPYJ)
            {
                return GetInt(7, 7, 7);
            }
            else
            {
                return GetInt(8, 7, 7);
            }
        }
        set
        {
            if (_culture == ConquestGameCode.VPYJ)
            {
                SetInt(7, 7, 7, value);
            }
            else
            {
                SetInt(8, 7, 7, value);
            }
        }
    }

    public int Sprite2
    {
        get
        {
            if (_culture == ConquestGameCode.VPYJ)
            {
                return GetInt(7, 14, 7);
            }
            else
            {
                return GetInt(8, 14, 7);
            }
        }
        set
        {
            if (_culture == ConquestGameCode.VPYJ)
            {
                SetInt(7, 14, 7, value);
            }
            else
            {
                SetInt(8, 14, 7, value);
            }
        }
    }

    public int Sprite3
    {
        get
        {
            if (_culture == ConquestGameCode.VPYJ)
            {
                return GetInt(7, 21, 7);
            }
            else
            {
                return GetInt(8, 21, 7);
            }
        }
        set
        {
            if (_culture == ConquestGameCode.VPYJ)
            {
                SetInt(7, 21, 7, value);
            }
            else
            {
                SetInt(8, 21, 7, value);
            }
        }
    }

    public BuildingFunctionId Function
    {
        get
        {
            if (_culture == ConquestGameCode.VPYJ)
            {
                return (BuildingFunctionId)GetInt(7, 28, 4);
            }
            else
            {
                return (BuildingFunctionId)GetInt(8, 28, 4);
            }
        }
        set
        {
            if (_culture == ConquestGameCode.VPYJ)
            {
                SetInt(7, 28, 4, (int)value);
            }
            else
            {
                SetInt(8, 28, 4, (int)value);
            }
        }
    }
}