// This file is automatically generated

using RanseiLink.Core.Enums;
using RanseiLink.Core.Graphics;

namespace RanseiLink.Core.Models;

public partial class Episode : BaseDataWindow
{
    public const int DataLength = 0x8;
    public Episode(byte[] data) : base(data, DataLength) { }
    public Episode() : this(new byte[DataLength]) { }

    public int Order
    {
        get => GetInt(0, 0, 9);
        set => SetInt(0, 0, 9, value);
    }

    public ScenarioId Scenario
    {
        get => (ScenarioId)GetInt(0, 9, 4);
        set => SetInt(0, 9, 4, (int)value);
    }

    public EpisodeId UnlockCondition
    {
        get => (EpisodeId)GetInt(1, 0, 6);
        set => SetInt(1, 0, 6, (int)value);
    }

    public int Difficulty
    {
        get => GetInt(1, 6, 3);
        set => SetInt(1, 6, 3, value);
    }

    public EpisodeClearConditionId ClearCondition
    {
        get => (EpisodeClearConditionId)GetInt(1, 26, 4);
        set => SetInt(1, 26, 4, (int)value);
    }

    public bool GetIsStartKingdom(KingdomId kingdomId)
    {
        return GetIsStartKingdom((int)kingdomId);
    }

    public bool GetIsStartKingdom(int kingdomId)
    {
        return GetInt(0, 13 + kingdomId, 1) == 1;
    }

    public void SetIsStartKingdom(KingdomId kingdomId, bool value)
    {
        SetIsStartKingdom((int)kingdomId, value);
    }

    public void SetIsStartKingdom(int kingdomId, bool value)
    {
        SetInt(0, 13 + kingdomId, 1, value ? 1 : 0);
    }

    public bool GetIsUnlockedKingdom(KingdomId kingdomId)
    {
        return GetIsUnlockedKingdom((int)kingdomId);
    }

    public bool GetIsUnlockedKingdom(int kingdomId)
    {
        return GetInt(1, 9 + kingdomId, 1) == 1;
    }

    public void SetIsUnlockedKingdom(KingdomId kingdomId, bool value)
    {
        SetIsUnlockedKingdom((int)kingdomId, value);
    }

    public void SetIsUnlockedKingdom(int kingdomId, bool value)
    {
        SetInt(1, 9 + kingdomId, 1, value ? 1 : 0);
    }
}