// This file is automatically generated

#nullable enable

using RanseiLink.Core.Enums;
using RanseiLink.Core.Graphics;

namespace RanseiLink.Core.Models;

public partial class Episode : BaseDataWindow
{
    public const int DataLength = 0x8;
    public Episode(byte[] data) : base(data, DataLength) { }
    public Episode() : this(new byte[DataLength]) { }

    public int ScenarioWarrior
    {
        get => GetInt(0, 0, 9);
        set => SetInt(0, 0, 9, value);
    }

    public ScenarioId Scenario
    {
        get => (ScenarioId)GetInt(0, 9, 4);
        set => SetInt(0, 9, 4, (int)value);
    }

    public bool GetIsStartKingdom(KingdomId id)
    {
        return GetIsStartKingdom((int)id);
    }

    public bool GetIsStartKingdom(int id)
    {
        return GetInt(0, 13 + id, 1) == 1;
    }

    public void SetIsStartKingdom(KingdomId id, bool value)
    {
        SetIsStartKingdom((int)id, value);
    }

    public void SetIsStartKingdom(int id, bool value)
    {
        SetInt(0, 13 + id, 1, value ? 1 : 0);
    }

    public EpisodeId UnlockCondition
    {
        get => (EpisodeId)GetInt(1, 0, 6);
        set => SetInt(1, 0, 6, (int)value);
    }

    public int Difficulty
    {
        get => GetInt(1, 6, 3);
        set => SetInt(1, 6, 3, value);
    }

    public bool GetIsUnlockedKingdom(KingdomId id)
    {
        return GetIsUnlockedKingdom((int)id);
    }

    public bool GetIsUnlockedKingdom(int id)
    {
        return GetInt(1, 9 + id, 1) == 1;
    }

    public void SetIsUnlockedKingdom(KingdomId id, bool value)
    {
        SetIsUnlockedKingdom((int)id, value);
    }

    public void SetIsUnlockedKingdom(int id, bool value)
    {
        SetInt(1, 9 + id, 1, value ? 1 : 0);
    }

    public EpisodeClearConditionId ClearCondition
    {
        get => (EpisodeClearConditionId)GetInt(1, 26, 3);
        set => SetInt(1, 26, 3, (int)value);
    }
}