// This file is automatically generated

using RanseiLink.Core.Enums;
using RanseiLink.Core.Graphics;

namespace RanseiLink.Core.Models;

public class GimmickObject : BaseDataWindow
{
    public const int DataLength = 0x4;
    public GimmickObject(byte[] data) : base(data, DataLength) { }
    public GimmickObject() : this(new byte[DataLength]) { }
}