// This file is automatically generated

#nullable enable

using RanseiLink.Core.Enums;
using RanseiLink.Core.Graphics;

namespace RanseiLink.Core.Models;

public partial class Gimmick : BaseDataWindow
{
    private ConquestGameCode _culture;
    public static int DataLength(ConquestGameCode culture)
    {
        return culture switch
        {
            ConquestGameCode.VPYJ => 0x24,
            _ => 0x28
        };
    }
    public Gimmick(byte[] data, ConquestGameCode culture) : base(data, DataLength(culture)) { _culture = culture; }
    public Gimmick(ConquestGameCode culture) : this(new byte[DataLength(culture)], culture) { }

    public int Name_MaxLength
    {
        get
        {
            if (_culture == ConquestGameCode.VPYJ)
            {
                return 14;
            }
            else
            {
                return 16;
            }
        }
    }
    public string Name
    {
        get => GetPaddedUtf8String(0, Name_MaxLength);
        set => SetPaddedUtf8String(0, Name_MaxLength, value);
    }

    public int Image1
    {
        get
        {
            if (_culture == ConquestGameCode.VPYJ)
            {
                return GetByte(15);
            }
            else
            {
                return GetByte(17);
            }
        }
        set
        {
            if (_culture == ConquestGameCode.VPYJ)
            {
                SetByte(15, (byte)value);
            }
            else
            {
                SetByte(17, (byte)value);
            }
        }
    }

    public TypeId AttackType
    {
        get
        {
            if (_culture == ConquestGameCode.VPYJ)
            {
                return (TypeId)GetInt(4, 0, 5);
            }
            else
            {
                return (TypeId)GetInt(5, 0, 5);
            }
        }
        set
        {
            if (_culture == ConquestGameCode.VPYJ)
            {
                SetInt(4, 0, 5, (int)value);
            }
            else
            {
                SetInt(5, 0, 5, (int)value);
            }
        }
    }

    public TypeId DestroyType
    {
        get
        {
            if (_culture == ConquestGameCode.VPYJ)
            {
                return (TypeId)GetInt(4, 5, 5);
            }
            else
            {
                return (TypeId)GetInt(5, 5, 5);
            }
        }
        set
        {
            if (_culture == ConquestGameCode.VPYJ)
            {
                SetInt(4, 5, 5, (int)value);
            }
            else
            {
                SetInt(5, 5, 5, (int)value);
            }
        }
    }

    public bool IsLog
    {
        get
        {
            if (_culture == ConquestGameCode.VPYJ)
            {
                return GetInt(4, 10, 1) == 1;
            }
            else
            {
                return GetInt(5, 10, 1) == 1;
            }
        }
        set
        {
            if (_culture == ConquestGameCode.VPYJ)
            {
                SetInt(4, 10, 1, value ? 1 : 0);
            }
            else
            {
                SetInt(5, 10, 1, value ? 1 : 0);
            }
        }
    }

    public GimmickObjectId State1Sprite
    {
        get
        {
            if (_culture == ConquestGameCode.VPYJ)
            {
                return (GimmickObjectId)GetInt(4, 11, 7);
            }
            else
            {
                return (GimmickObjectId)GetInt(5, 11, 7);
            }
        }
        set
        {
            if (_culture == ConquestGameCode.VPYJ)
            {
                SetInt(4, 11, 7, (int)value);
            }
            else
            {
                SetInt(5, 11, 7, (int)value);
            }
        }
    }

    public GimmickObjectId State2Sprite
    {
        get
        {
            if (_culture == ConquestGameCode.VPYJ)
            {
                return (GimmickObjectId)GetInt(4, 18, 7);
            }
            else
            {
                return (GimmickObjectId)GetInt(5, 18, 7);
            }
        }
        set
        {
            if (_culture == ConquestGameCode.VPYJ)
            {
                SetInt(4, 18, 7, (int)value);
            }
            else
            {
                SetInt(5, 18, 7, (int)value);
            }
        }
    }

    public MoveEffectId Effect
    {
        get
        {
            if (_culture == ConquestGameCode.VPYJ)
            {
                return (MoveEffectId)GetInt(4, 25, 7);
            }
            else
            {
                return (MoveEffectId)GetInt(5, 25, 7);
            }
        }
        set
        {
            if (_culture == ConquestGameCode.VPYJ)
            {
                SetInt(4, 25, 7, (int)value);
            }
            else
            {
                SetInt(5, 25, 7, (int)value);
            }
        }
    }

    public int AttackPower
    {
        get
        {
            if (_culture == ConquestGameCode.VPYJ)
            {
                return GetInt(5, 0, 8);
            }
            else
            {
                return GetInt(6, 0, 8);
            }
        }
        set
        {
            if (_culture == ConquestGameCode.VPYJ)
            {
                SetInt(5, 0, 8, value);
            }
            else
            {
                SetInt(6, 0, 8, value);
            }
        }
    }

    public int Anim1
    {
        get
        {
            if (_culture == ConquestGameCode.VPYJ)
            {
                return GetInt(5, 8, 8);
            }
            else
            {
                return GetInt(6, 8, 8);
            }
        }
        set
        {
            if (_culture == ConquestGameCode.VPYJ)
            {
                SetInt(5, 8, 8, value);
            }
            else
            {
                SetInt(6, 8, 8, value);
            }
        }
    }

    public int Anim2
    {
        get
        {
            if (_culture == ConquestGameCode.VPYJ)
            {
                return GetInt(5, 16, 8);
            }
            else
            {
                return GetInt(6, 16, 8);
            }
        }
        set
        {
            if (_culture == ConquestGameCode.VPYJ)
            {
                SetInt(5, 16, 8, value);
            }
            else
            {
                SetInt(6, 16, 8, value);
            }
        }
    }

    public GimmickId GimmickRef1
    {
        get
        {
            if (_culture == ConquestGameCode.VPYJ)
            {
                return (GimmickId)GetInt(5, 24, 8);
            }
            else
            {
                return (GimmickId)GetInt(6, 24, 8);
            }
        }
        set
        {
            if (_culture == ConquestGameCode.VPYJ)
            {
                SetInt(5, 24, 8, (int)value);
            }
            else
            {
                SetInt(6, 24, 8, (int)value);
            }
        }
    }

    public int Unknown_7_0_5
    {
        get
        {
            if (_culture == ConquestGameCode.VPYJ)
            {
                return GetInt(6, 0, 5);
            }
            else
            {
                return GetInt(7, 0, 5);
            }
        }
        set
        {
            if (_culture == ConquestGameCode.VPYJ)
            {
                SetInt(6, 0, 5, value);
            }
            else
            {
                SetInt(7, 0, 5, value);
            }
        }
    }

    public int Unknown_7_5_5
    {
        get
        {
            if (_culture == ConquestGameCode.VPYJ)
            {
                return GetInt(6, 5, 5);
            }
            else
            {
                return GetInt(7, 5, 5);
            }
        }
        set
        {
            if (_culture == ConquestGameCode.VPYJ)
            {
                SetInt(6, 5, 5, value);
            }
            else
            {
                SetInt(7, 5, 5, value);
            }
        }
    }

    public int Unknown_7_10_5
    {
        get
        {
            if (_culture == ConquestGameCode.VPYJ)
            {
                return GetInt(6, 10, 5);
            }
            else
            {
                return GetInt(7, 10, 5);
            }
        }
        set
        {
            if (_culture == ConquestGameCode.VPYJ)
            {
                SetInt(6, 10, 5, value);
            }
            else
            {
                SetInt(7, 10, 5, value);
            }
        }
    }

    public int Unknown_7_15_5
    {
        get
        {
            if (_culture == ConquestGameCode.VPYJ)
            {
                return GetInt(6, 15, 5);
            }
            else
            {
                return GetInt(7, 15, 5);
            }
        }
        set
        {
            if (_culture == ConquestGameCode.VPYJ)
            {
                SetInt(6, 15, 5, value);
            }
            else
            {
                SetInt(7, 15, 5, value);
            }
        }
    }

    public int Unknown_7_20_12
    {
        get
        {
            if (_culture == ConquestGameCode.VPYJ)
            {
                return GetInt(6, 20, 12);
            }
            else
            {
                return GetInt(7, 20, 12);
            }
        }
        set
        {
            if (_culture == ConquestGameCode.VPYJ)
            {
                SetInt(6, 20, 12, value);
            }
            else
            {
                SetInt(7, 20, 12, value);
            }
        }
    }

    public int Unknown_8_0_8
    {
        get
        {
            if (_culture == ConquestGameCode.VPYJ)
            {
                return GetInt(7, 0, 8);
            }
            else
            {
                return GetInt(8, 0, 8);
            }
        }
        set
        {
            if (_culture == ConquestGameCode.VPYJ)
            {
                SetInt(7, 0, 8, value);
            }
            else
            {
                SetInt(8, 0, 8, value);
            }
        }
    }

    public int Unknown_8_8_8
    {
        get
        {
            if (_culture == ConquestGameCode.VPYJ)
            {
                return GetInt(7, 8, 8);
            }
            else
            {
                return GetInt(8, 8, 8);
            }
        }
        set
        {
            if (_culture == ConquestGameCode.VPYJ)
            {
                SetInt(7, 8, 8, value);
            }
            else
            {
                SetInt(8, 8, 8, value);
            }
        }
    }

    public int Unknown_8_16_3
    {
        get
        {
            if (_culture == ConquestGameCode.VPYJ)
            {
                return GetInt(7, 16, 3);
            }
            else
            {
                return GetInt(8, 16, 3);
            }
        }
        set
        {
            if (_culture == ConquestGameCode.VPYJ)
            {
                SetInt(7, 16, 3, value);
            }
            else
            {
                SetInt(8, 16, 3, value);
            }
        }
    }

    public int Unknown_8_24_3
    {
        get
        {
            if (_culture == ConquestGameCode.VPYJ)
            {
                return GetInt(7, 24, 3);
            }
            else
            {
                return GetInt(8, 24, 3);
            }
        }
        set
        {
            if (_culture == ConquestGameCode.VPYJ)
            {
                SetInt(7, 24, 3, value);
            }
            else
            {
                SetInt(8, 24, 3, value);
            }
        }
    }

    public int Unknown_9_0_4
    {
        get
        {
            if (_culture == ConquestGameCode.VPYJ)
            {
                return GetInt(8, 0, 4);
            }
            else
            {
                return GetInt(9, 0, 4);
            }
        }
        set
        {
            if (_culture == ConquestGameCode.VPYJ)
            {
                SetInt(8, 0, 4, value);
            }
            else
            {
                SetInt(9, 0, 4, value);
            }
        }
    }

    public GimmickId GimmickRef2
    {
        get
        {
            if (_culture == ConquestGameCode.VPYJ)
            {
                return (GimmickId)GetInt(8, 4, 8);
            }
            else
            {
                return (GimmickId)GetInt(9, 4, 8);
            }
        }
        set
        {
            if (_culture == ConquestGameCode.VPYJ)
            {
                SetInt(8, 4, 8, (int)value);
            }
            else
            {
                SetInt(9, 4, 8, (int)value);
            }
        }
    }

    public int Image2
    {
        get
        {
            if (_culture == ConquestGameCode.VPYJ)
            {
                return GetInt(8, 12, 8);
            }
            else
            {
                return GetInt(9, 12, 8);
            }
        }
        set
        {
            if (_culture == ConquestGameCode.VPYJ)
            {
                SetInt(8, 12, 8, value);
            }
            else
            {
                SetInt(9, 12, 8, value);
            }
        }
    }

    public int Image3
    {
        get
        {
            if (_culture == ConquestGameCode.VPYJ)
            {
                return GetInt(8, 20, 8);
            }
            else
            {
                return GetInt(9, 20, 8);
            }
        }
        set
        {
            if (_culture == ConquestGameCode.VPYJ)
            {
                SetInt(8, 20, 8, value);
            }
            else
            {
                SetInt(9, 20, 8, value);
            }
        }
    }

    public GimmickRangeId Range
    {
        get
        {
            if (_culture == ConquestGameCode.VPYJ)
            {
                return (GimmickRangeId)GetInt(7, 19, 5);
            }
            else
            {
                return (GimmickRangeId)GetInt(8, 19, 5);
            }
        }
        set
        {
            if (_culture == ConquestGameCode.VPYJ)
            {
                SetInt(7, 19, 5, (int)value);
            }
            else
            {
                SetInt(8, 19, 5, (int)value);
            }
        }
    }
}