// This file is automatically generated

#nullable enable

using RanseiLink.Core.Enums;
using RanseiLink.Core.Graphics;

namespace RanseiLink.Core.Models;

public partial class Item : BaseDataWindow, INamedModel
{
    public event EventHandler? NameChanged;
    public const int DataLength = 0x24;
    public Item(byte[] data) : base(data, DataLength) { }
    public Item() : this(new byte[DataLength]) { }

    public int Name_MaxLength
    {
        get => 20;
    }
    public string Name
    {
        get => GetPaddedUtf8String(0, Name_MaxLength);
        set
        {
            SetPaddedUtf8String(0, Name_MaxLength, value);
            NameChanged?.Invoke(this, EventArgs.Empty);
        }
    }

    public int Unknown_5_8_1
    {
        get => GetInt(5, 8, 1);
        set => SetInt(5, 8, 1, value);
    }

    public int Unknown_5_9_5
    {
        get => GetInt(5, 9, 5);
        set => SetInt(5, 9, 5, value);
    }

    public int Unknown_5_14_2
    {
        get => GetInt(5, 14, 2);
        set => SetInt(5, 14, 2, value);
    }

    public PurchaseMethodId PurchaseMethod
    {
        get => (PurchaseMethodId)GetInt(5, 16, 3);
        set => SetInt(5, 16, 3, (int)value);
    }

    public ItemCategoryId Category
    {
        get => (ItemCategoryId)GetInt(5, 19, 2);
        set => SetInt(5, 19, 2, (int)value);
    }

    public ItemEffectId Effect
    {
        get => (ItemEffectId)GetInt(5, 21, 5);
        set => SetInt(5, 21, 5, (int)value);
    }

    public int EffectDuration
    {
        get => GetInt(5, 26, 5);
        set => SetInt(5, 26, 5, value);
    }

    public int Unknown_5_31_1
    {
        get => GetInt(5, 31, 1);
        set => SetInt(5, 31, 1, value);
    }

    public ItemId CraftingIngredient1
    {
        get => (ItemId)GetInt(6, 0, 9);
        set => SetInt(6, 0, 9, (int)value);
    }

    public int CraftingIngredient1Amount
    {
        get => GetInt(6, 9, 7);
        set => SetInt(6, 9, 7, value);
    }

    public ItemId CraftingIngredient2
    {
        get => (ItemId)GetInt(6, 16, 9);
        set => SetInt(6, 16, 9, (int)value);
    }

    public int CraftingIngredient2Amount
    {
        get => GetInt(6, 25, 7);
        set => SetInt(6, 25, 7, value);
    }

    public ItemId UnknownItem
    {
        get => (ItemId)GetInt(7, 0, 9);
        set => SetInt(7, 0, 9, (int)value);
    }

    public int ShopPriceMultiplier
    {
        get => GetInt(7, 9, 9);
        set => SetInt(7, 9, 9, value);
    }

    public int Effect_Quantity
    {
        get => GetInt(7, 18, 9);
        set => SetInt(7, 18, 9, value);
    }

    public int EffectModifier
    {
        get => GetInt(7, 18, 9);
        set => SetInt(7, 18, 9, value);
    }

    public bool GetPurchasable(KingdomId id)
    {
        return GetPurchasable((int)id);
    }

    public bool GetPurchasable(int id)
    {
        return GetInt(8, 0 + id, 1) == 1;
    }

    public void SetPurchasable(KingdomId id, bool value)
    {
        SetPurchasable((int)id, value);
    }

    public void SetPurchasable(int id, bool value)
    {
        SetInt(8, 0 + id, 1, value ? 1 : 0);
    }
}