// This file is automatically generated

#nullable enable

using RanseiLink.Core.Enums;
using RanseiLink.Core.Graphics;

namespace RanseiLink.Core.Models;

public partial class Kingdom : BaseDataWindow, INamedModel
{
    public event EventHandler? NameChanged;
    private ConquestGameCode _culture;
    public static int DataLength(ConquestGameCode culture)
    {
        return culture switch
        {
            ConquestGameCode.VPYJ => 0x14,
            _ => 0x18
        };
    }
    public Kingdom(byte[] data, ConquestGameCode culture) : base(data, DataLength(culture)) { _culture = culture; }
    public Kingdom(ConquestGameCode culture) : this(new byte[DataLength(culture)], culture) { }

    public int Name_MaxLength
    {
        get
        {
            if (_culture == ConquestGameCode.VPYJ)
            {
                return 8;
            }
            else
            {
                return 10;
            }
        }
    }
    public string Name
    {
        get => GetPaddedUtf8String(0, Name_MaxLength);
        set
        {
            SetPaddedUtf8String(0, Name_MaxLength, value);
            NameChanged?.Invoke(this, EventArgs.Empty);
        }
    }

    public int Unknown_2_24_3
    {
        get
        {
            if (_culture == ConquestGameCode.VPYJ)
            {
                return GetInt(2, 8, 3);
            }
            else
            {
                return GetInt(2, 24, 3);
            }
        }
        set
        {
            if (_culture == ConquestGameCode.VPYJ)
            {
                SetInt(2, 8, 3, value);
            }
            else
            {
                SetInt(2, 24, 3, value);
            }
        }
    }

    public KingdomId MapConnection0
    {
        get
        {
            if (_culture == ConquestGameCode.VPYJ)
            {
                return (KingdomId)GetInt(2, 0, 5);
            }
            else
            {
                return (KingdomId)GetInt(3, 0, 5);
            }
        }
        set
        {
            if (_culture == ConquestGameCode.VPYJ)
            {
                SetInt(2, 0, 5, (int)value);
            }
            else
            {
                SetInt(3, 0, 5, (int)value);
            }
        }
    }

    public KingdomId MapConnection1
    {
        get
        {
            if (_culture == ConquestGameCode.VPYJ)
            {
                return (KingdomId)GetInt(2, 5, 5);
            }
            else
            {
                return (KingdomId)GetInt(3, 5, 5);
            }
        }
        set
        {
            if (_culture == ConquestGameCode.VPYJ)
            {
                SetInt(2, 5, 5, (int)value);
            }
            else
            {
                SetInt(3, 5, 5, (int)value);
            }
        }
    }

    public KingdomId MapConnection2
    {
        get
        {
            if (_culture == ConquestGameCode.VPYJ)
            {
                return (KingdomId)GetInt(2, 10, 5);
            }
            else
            {
                return (KingdomId)GetInt(3, 10, 5);
            }
        }
        set
        {
            if (_culture == ConquestGameCode.VPYJ)
            {
                SetInt(2, 10, 5, (int)value);
            }
            else
            {
                SetInt(3, 10, 5, (int)value);
            }
        }
    }

    public KingdomId MapConnection4
    {
        get
        {
            if (_culture == ConquestGameCode.VPYJ)
            {
                return (KingdomId)GetInt(2, 11, 5);
            }
            else
            {
                return (KingdomId)GetInt(2, 27, 5);
            }
        }
        set
        {
            if (_culture == ConquestGameCode.VPYJ)
            {
                SetInt(2, 11, 5, (int)value);
            }
            else
            {
                SetInt(2, 27, 5, (int)value);
            }
        }
    }

    public KingdomId MapConnection3
    {
        get
        {
            if (_culture == ConquestGameCode.VPYJ)
            {
                return (KingdomId)GetInt(3, 0, 5);
            }
            else
            {
                return (KingdomId)GetInt(4, 0, 5);
            }
        }
        set
        {
            if (_culture == ConquestGameCode.VPYJ)
            {
                SetInt(3, 0, 5, (int)value);
            }
            else
            {
                SetInt(4, 0, 5, (int)value);
            }
        }
    }

    public KingdomId MapConnection5
    {
        get
        {
            if (_culture == ConquestGameCode.VPYJ)
            {
                return (KingdomId)GetInt(3, 5, 5);
            }
            else
            {
                return (KingdomId)GetInt(4, 5, 5);
            }
        }
        set
        {
            if (_culture == ConquestGameCode.VPYJ)
            {
                SetInt(3, 5, 5, (int)value);
            }
            else
            {
                SetInt(4, 5, 5, (int)value);
            }
        }
    }

    public KingdomId MapConnection6
    {
        get
        {
            if (_culture == ConquestGameCode.VPYJ)
            {
                return (KingdomId)GetInt(3, 10, 5);
            }
            else
            {
                return (KingdomId)GetInt(4, 10, 5);
            }
        }
        set
        {
            if (_culture == ConquestGameCode.VPYJ)
            {
                SetInt(3, 10, 5, (int)value);
            }
            else
            {
                SetInt(4, 10, 5, (int)value);
            }
        }
    }

    public KingdomId MapConnection7
    {
        get
        {
            if (_culture == ConquestGameCode.VPYJ)
            {
                return (KingdomId)GetInt(3, 15, 5);
            }
            else
            {
                return (KingdomId)GetInt(4, 15, 5);
            }
        }
        set
        {
            if (_culture == ConquestGameCode.VPYJ)
            {
                SetInt(3, 15, 5, (int)value);
            }
            else
            {
                SetInt(4, 15, 5, (int)value);
            }
        }
    }

    public KingdomId MapConnection8
    {
        get
        {
            if (_culture == ConquestGameCode.VPYJ)
            {
                return (KingdomId)GetInt(3, 20, 5);
            }
            else
            {
                return (KingdomId)GetInt(4, 20, 5);
            }
        }
        set
        {
            if (_culture == ConquestGameCode.VPYJ)
            {
                SetInt(3, 20, 5, (int)value);
            }
            else
            {
                SetInt(4, 20, 5, (int)value);
            }
        }
    }

    public KingdomId MapConnection9
    {
        get
        {
            if (_culture == ConquestGameCode.VPYJ)
            {
                return (KingdomId)GetInt(3, 25, 5);
            }
            else
            {
                return (KingdomId)GetInt(4, 25, 5);
            }
        }
        set
        {
            if (_culture == ConquestGameCode.VPYJ)
            {
                SetInt(3, 25, 5, (int)value);
            }
            else
            {
                SetInt(4, 25, 5, (int)value);
            }
        }
    }

    public KingdomId MapConnection10
    {
        get
        {
            if (_culture == ConquestGameCode.VPYJ)
            {
                return (KingdomId)GetInt(4, 0, 5);
            }
            else
            {
                return (KingdomId)GetInt(5, 0, 5);
            }
        }
        set
        {
            if (_culture == ConquestGameCode.VPYJ)
            {
                SetInt(4, 0, 5, (int)value);
            }
            else
            {
                SetInt(5, 0, 5, (int)value);
            }
        }
    }

    public KingdomId MapConnection11
    {
        get
        {
            if (_culture == ConquestGameCode.VPYJ)
            {
                return (KingdomId)GetInt(4, 5, 5);
            }
            else
            {
                return (KingdomId)GetInt(5, 5, 5);
            }
        }
        set
        {
            if (_culture == ConquestGameCode.VPYJ)
            {
                SetInt(4, 5, 5, (int)value);
            }
            else
            {
                SetInt(5, 5, 5, (int)value);
            }
        }
    }

    public KingdomId MapConnection12
    {
        get
        {
            if (_culture == ConquestGameCode.VPYJ)
            {
                return (KingdomId)GetInt(4, 10, 5);
            }
            else
            {
                return (KingdomId)GetInt(5, 10, 5);
            }
        }
        set
        {
            if (_culture == ConquestGameCode.VPYJ)
            {
                SetInt(4, 10, 5, (int)value);
            }
            else
            {
                SetInt(5, 10, 5, (int)value);
            }
        }
    }

    public BattleConfigId BattleConfig
    {
        get
        {
            if (_culture == ConquestGameCode.VPYJ)
            {
                return (BattleConfigId)GetInt(4, 15, 7);
            }
            else
            {
                return (BattleConfigId)GetInt(5, 15, 7);
            }
        }
        set
        {
            if (_culture == ConquestGameCode.VPYJ)
            {
                SetInt(4, 15, 7, (int)value);
            }
            else
            {
                SetInt(5, 15, 7, (int)value);
            }
        }
    }

    public PokemonId SwarmPokemon
    {
        get
        {
            if (_culture == ConquestGameCode.VPYJ)
            {
                return (PokemonId)GetInt(4, 22, 8);
            }
            else
            {
                return (PokemonId)GetInt(5, 22, 8);
            }
        }
        set
        {
            if (_culture == ConquestGameCode.VPYJ)
            {
                SetInt(4, 22, 8, (int)value);
            }
            else
            {
                SetInt(5, 22, 8, (int)value);
            }
        }
    }
}