// This file is automatically generated

#nullable enable

using RanseiLink.Core.Enums;
using RanseiLink.Core.Graphics;

namespace RanseiLink.Core.Models;

public partial class MapPoint : BaseDataWindow
{
    public const int DataLength = 0x28;
    public MapPoint(byte[] data) : base(data, DataLength) { }
    public MapPoint() : this(new byte[DataLength]) { }

    public GimmickId Gimmick
    {
        get => (GimmickId)GetInt(0, 0, 8);
        set => SetInt(0, 0, 8, (int)value);
    }

    public int Cell
    {
        get => GetInt(0, 8, 9);
        set => SetInt(0, 8, 9, value);
    }

    public int Unknown_0_17_2
    {
        get => GetInt(0, 17, 2);
        set => SetInt(0, 17, 2, value);
    }

    public int Unknown_0_19_1
    {
        get => GetInt(0, 19, 1);
        set => SetInt(0, 19, 1, value);
    }

    public int Unknown_0_20_1
    {
        get => GetInt(0, 20, 1);
        set => SetInt(0, 20, 1, value);
    }

    public int Unknown_0_21_5
    {
        get => GetInt(0, 21, 5);
        set => SetInt(0, 21, 5, value);
    }

    public int Unknown_0_26_6
    {
        get => GetInt(0, 26, 6);
        set => SetInt(0, 26, 6, value);
    }

    public int Unknown_1_0_8
    {
        get => GetInt(1, 0, 8);
        set => SetInt(1, 0, 8, value);
    }

    public int Unknown_1_8_9
    {
        get => GetInt(1, 8, 9);
        set => SetInt(1, 8, 9, value);
    }

    public int Unknown_1_17_7
    {
        get => GetInt(1, 17, 7);
        set => SetInt(1, 17, 7, value);
    }

    public int Unknown_1_24_3
    {
        get => GetInt(1, 24, 3);
        set => SetInt(1, 24, 3, value);
    }

    public int Unknown_1_27_4
    {
        get => GetInt(1, 27, 4);
        set => SetInt(1, 27, 4, value);
    }

    public int Unknown_1_31_1
    {
        get => GetInt(1, 31, 1);
        set => SetInt(1, 31, 1, value);
    }
}