// This file is automatically generated

#nullable enable

using RanseiLink.Core.Enums;
using RanseiLink.Core.Graphics;

namespace RanseiLink.Core.Models;

public partial class MoveAnimation : BaseDataWindow
{
    public const int DataLength = 0x4;
    public MoveAnimation(byte[] data) : base(data, DataLength) { }
    public MoveAnimation() : this(new byte[DataLength]) { }

    public TrueMoveAnimationId Animation
    {
        get => (TrueMoveAnimationId)GetInt(0, 0, 8);
        set => SetInt(0, 0, 8, (int)value);
    }

    public int Unknown
    {
        get => GetInt(0, 16, 8);
        set => SetInt(0, 16, 8, value);
    }
}