// This file is automatically generated

using RanseiLink.Core.Enums;
using RanseiLink.Core.Graphics;

namespace RanseiLink.Core.Models;

public class MoveAnimation : BaseDataWindow
{
    public const int DataLength = 0x4;
    public MoveAnimation(byte[] data) : base(data, DataLength) { }
    public MoveAnimation() : this(new byte[DataLength]) { }

    public int UnknownA
    {
        get => GetInt(0, 0, 16);
        set => SetInt(0, 0, 16, value);
    }

    public int UnknownB
    {
        get => GetInt(0, 16, 16);
        set => SetInt(0, 16, 16, value);
    }
}