// This file is automatically generated

#nullable enable

using RanseiLink.Core.Enums;
using RanseiLink.Core.Graphics;

namespace RanseiLink.Core.Models;

public partial class Pokemon : BaseDataWindow, INamedModel
{
    public event EventHandler? NameChanged;
    public const int DataLength = 0x30;
    public Pokemon(byte[] data) : base(data, DataLength) { }
    public Pokemon() : this(new byte[DataLength]) { }

    public int Name_MaxLength
    {
        get => 10;
    }
    public string Name
    {
        get => GetPaddedUtf8String(0, Name_MaxLength);
        set
        {
            SetPaddedUtf8String(0, Name_MaxLength, value);
            NameChanged?.Invoke(this, EventArgs.Empty);
        }
    }

    public int CatchRate
    {
        get => GetInt(2, 24, 8);
        set => SetInt(2, 24, 8, value);
    }

    public int Hp
    {
        get => GetInt(3, 0, 10);
        set => SetInt(3, 0, 10, value);
    }

    public EvolutionConditionId EvolutionCondition1
    {
        get => (EvolutionConditionId)GetInt(3, 10, 4);
        set => SetInt(3, 10, 4, (int)value);
    }

    public EvolutionConditionId EvolutionCondition2
    {
        get => (EvolutionConditionId)GetInt(3, 14, 4);
        set => SetInt(3, 14, 4, (int)value);
    }

    public int Section2Index
    {
        get => GetInt(3, 18, 5);
        set => SetInt(3, 18, 5, value);
    }

    public int BattleIntroSpriteOffset
    {
        get => GetInt(3, 23, 3);
        set => SetInt(3, 23, 3, value);
    }

    public int Weight
    {
        get => GetInt(3, 26, 3);
        set => SetInt(3, 26, 3, value);
    }

    public IdleMotionId IdleMotion
    {
        get => (IdleMotionId)GetInt(3, 29, 2);
        set => SetInt(3, 29, 2, (int)value);
    }

    public int Atk
    {
        get => GetInt(4, 0, 10);
        set => SetInt(4, 0, 10, value);
    }

    public int Def
    {
        get => GetInt(4, 10, 10);
        set => SetInt(4, 10, 10, value);
    }

    public int Spe
    {
        get => GetInt(4, 20, 10);
        set => SetInt(4, 20, 10, value);
    }

    public bool IsLegendary
    {
        get => GetInt(4, 30, 1) == 1;
        set => SetInt(4, 30, 1, value ? 1 : 0);
    }

    public bool AsymmetricBattleSprite
    {
        get => GetInt(4, 31, 1) == 1;
        set => SetInt(4, 31, 1, value ? 1 : 0);
    }

    public TypeId Type1
    {
        get => (TypeId)GetInt(5, 0, 5);
        set => SetInt(5, 0, 5, (int)value);
    }

    public TypeId Type2
    {
        get => (TypeId)GetInt(5, 5, 5);
        set => SetInt(5, 5, 5, (int)value);
    }

    public MoveId Move
    {
        get => (MoveId)GetInt(5, 10, 9);
        set => SetInt(5, 10, 9, (int)value);
    }

    public int EvolutionCondition2_Quantity2
    {
        get => GetInt(5, 19, 9);
        set => SetInt(5, 19, 9, value);
    }

    public AbilityId Ability1
    {
        get => (AbilityId)GetInt(6, 0, 9);
        set => SetInt(6, 0, 9, (int)value);
    }

    public AbilityId Ability2
    {
        get => (AbilityId)GetInt(6, 9, 9);
        set => SetInt(6, 9, 9, (int)value);
    }

    public AbilityId Ability3
    {
        get => (AbilityId)GetInt(6, 18, 9);
        set => SetInt(6, 18, 9, (int)value);
    }

    public int EvolutionCondition1_Quantity1
    {
        get => GetInt(7, 0, 9);
        set => SetInt(7, 0, 9, value);
    }

    public int EvolutionCondition1_Quantity2
    {
        get => GetInt(7, 9, 9);
        set => SetInt(7, 9, 9, value);
    }

    public int EvolutionCondition2_Quantity1
    {
        get => GetInt(7, 18, 9);
        set => SetInt(7, 18, 9, value);
    }

    public int MovementRange
    {
        get => GetInt(7, 27, 4);
        set => SetInt(7, 27, 4, value);
    }

    public bool LongAttackAnimation
    {
        get => GetInt(7, 31, 1) == 1;
        set => SetInt(7, 31, 1, value ? 1 : 0);
    }

    public int MinEvolutionTableEntry
    {
        get => GetInt(8, 0, 11);
        set => SetInt(8, 0, 11, value);
    }

    public int MaxEvolutionTableEntry
    {
        get => GetInt(8, 11, 11);
        set => SetInt(8, 11, 11, value);
    }

    public int NationalPokedexNumber
    {
        get => GetInt(8, 22, 10);
        set => SetInt(8, 22, 10, value);
    }

    public int NameOrderIndex
    {
        get => GetInt(11, 0, 8);
        set => SetInt(11, 0, 8, value);
    }
}