// This file is automatically generated

#nullable enable

using RanseiLink.Core.Enums;
using RanseiLink.Core.Graphics;

namespace RanseiLink.Core.Models;

public partial class ScenarioPokemon : BaseDataWindow
{
    public const int DataLength = 0x8;
    public ScenarioPokemon(byte[] data) : base(data, DataLength) { }
    public ScenarioPokemon() : this(new byte[DataLength]) { }

    public byte U1
    {
        get => (byte)GetInt(0, 8, 9);
        set => SetInt(0, 8, 9, (int)value);
    }

    public int Exp
    {
        get => GetInt(0, 17, 15);
        set => SetInt(0, 17, 15, value);
    }

    public int HpIv
    {
        get => GetInt(1, 0, 5);
        set => SetInt(1, 0, 5, value);
    }

    public int AtkIv
    {
        get => GetInt(1, 5, 5);
        set => SetInt(1, 5, 5, value);
    }

    public int DefIv
    {
        get => GetInt(1, 10, 5);
        set => SetInt(1, 10, 5, value);
    }

    public int SpeIv
    {
        get => GetInt(1, 15, 5);
        set => SetInt(1, 15, 5, value);
    }

    public AbilityId Ability
    {
        get => (AbilityId)GetInt(1, 20, 9);
        set => SetInt(1, 20, 9, (int)value);
    }

    public EnergyId Energy
    {
        get => (EnergyId)GetInt(1, 29, 3);
        set => SetInt(1, 29, 3, (int)value);
    }
}