// This file is automatically generated

using RanseiLink.Core.Enums;
using RanseiLink.Core.Graphics;

namespace RanseiLink.Core.Models;

public partial class ScenarioPokemon : BaseDataWindow
{
    public const int DataLength = 0x8;
    public ScenarioPokemon(byte[] data) : base(data, DataLength) { }
    public ScenarioPokemon() : base(new byte[DataLength], DataLength) { }

    public AbilityId Ability
    {
        get => (AbilityId)GetInt(1, 20, 8);
        set => SetInt(1, 20, 8, (int)value);
    }

    public int HpIv
    {
        get => GetInt(1, 0, 5);
        set => SetInt(1, 0, 5, value);
    }

    public int AtkIv
    {
        get => GetInt(1, 5, 5);
        set => SetInt(1, 5, 5, value);
    }

    public int DefIv
    {
        get => GetInt(1, 10, 5);
        set => SetInt(1, 10, 5, value);
    }

    public int SpeIv
    {
        get => GetInt(1, 15, 5);
        set => SetInt(1, 15, 5, value);
    }

    public ushort Exp
    {
        get => (ushort)GetInt(0, 16, 16);
        set => SetInt(0, 16, 16, (int)value);
    }

    public byte U1
    {
        get => (byte)GetInt(0, 8, 8);
        set => SetInt(0, 8, 8, (int)value);
    }

    public EnergyId Energy
    {
        get => (EnergyId)GetInt(1, 29, 3);
        set => SetInt(1, 29, 3, (int)value);
    }
}