// This file is automatically generated

#nullable enable

using RanseiLink.Core.Enums;
using RanseiLink.Core.Graphics;

namespace RanseiLink.Core.Models;

public partial class ScenarioArmy : BaseDataWindow
{
    public const int DataLength = 0xA0;
    public ScenarioArmy(byte[] data) : base(data, DataLength) { }
    public ScenarioArmy() : this(new byte[DataLength]) { }

    public int Unknown_4_16_2
    {
        get => GetInt(4, 16, 2);
        set => SetInt(4, 16, 2, value);
    }

    public int Unknown_4_18_5
    {
        get => GetInt(4, 18, 5);
        set => SetInt(4, 18, 5, value);
    }

    public int Leader
    {
        get => GetInt(4, 23, 9);
        set => SetInt(4, 23, 9, value);
    }

    public int Money
    {
        get => GetInt(5, 0, 16);
        set => SetInt(5, 0, 16, value);
    }
}