// This file is automatically generated

#nullable enable

using RanseiLink.Core.Enums;
using RanseiLink.Core.Graphics;

namespace RanseiLink.Core.Models;

public partial class ScenarioWarrior : BaseDataWindow
{
    public const int DataLength = 0x20;
    public ScenarioWarrior(byte[] data) : base(data, DataLength) { }
    public ScenarioWarrior() : this(new byte[DataLength]) { }

    public WarriorId Warrior
    {
        get => (WarriorId)GetInt(0, 0, 9);
        set => SetInt(0, 0, 9, (int)value);
    }

    public WarriorClassId Class
    {
        get => (WarriorClassId)GetInt(0, 9, 3);
        set => SetInt(0, 9, 3, (int)value);
    }

    public KingdomId Kingdom
    {
        get => (KingdomId)GetInt(0, 12, 5);
        set => SetInt(0, 12, 5, (int)value);
    }

    public int Army
    {
        get => GetInt(0, 17, 5);
        set => SetInt(0, 17, 5, value);
    }

    public ItemId Item
    {
        get => (ItemId)GetInt(2, 2, 9);
        set => SetInt(2, 2, 9, (int)value);
    }
}