// This file is automatically generated

#nullable enable

using RanseiLink.Core.Enums;
using RanseiLink.Core.Graphics;

namespace RanseiLink.Core.Models;

public partial class WarriorSkill : BaseDataWindow
{
    private ConquestGameCode _culture;
    public static int DataLength(ConquestGameCode culture)
    {
        return culture switch
        {
            ConquestGameCode.VPYJ => 0x18,
            _ => 0x1C
        };
    }
    public WarriorSkill(byte[] data, ConquestGameCode culture) : base(data, DataLength(culture)) { _culture = culture; }
    public WarriorSkill(ConquestGameCode culture) : this(new byte[DataLength(culture)], culture) { }

    public int Name_MaxLength
    {
        get
        {
            if (_culture == ConquestGameCode.VPYJ)
            {
                return 0xE;
            }
            else
            {
                return 0x12;
            }
        }
    }
    public string Name
    {
        get => GetPaddedUtf8String(0, Name_MaxLength);
        set => SetPaddedUtf8String(0, Name_MaxLength, value);
    }

    public int Effect1Amount
    {
        get
        {
            if (_culture == ConquestGameCode.VPYJ)
            {
                return GetInt(3, 24, 8);
            }
            else
            {
                return GetInt(4, 24, 8);
            }
        }
        set
        {
            if (_culture == ConquestGameCode.VPYJ)
            {
                SetInt(3, 24, 8, value);
            }
            else
            {
                SetInt(4, 24, 8, value);
            }
        }
    }

    public WarriorSkillEffectId Effect1
    {
        get
        {
            if (_culture == ConquestGameCode.VPYJ)
            {
                return (WarriorSkillEffectId)GetInt(4, 0, 7);
            }
            else
            {
                return (WarriorSkillEffectId)GetInt(5, 0, 7);
            }
        }
        set
        {
            if (_culture == ConquestGameCode.VPYJ)
            {
                SetInt(4, 0, 7, (int)value);
            }
            else
            {
                SetInt(5, 0, 7, (int)value);
            }
        }
    }

    public WarriorSkillEffectId Effect2
    {
        get
        {
            if (_culture == ConquestGameCode.VPYJ)
            {
                return (WarriorSkillEffectId)GetInt(4, 7, 7);
            }
            else
            {
                return (WarriorSkillEffectId)GetInt(5, 7, 7);
            }
        }
        set
        {
            if (_culture == ConquestGameCode.VPYJ)
            {
                SetInt(4, 7, 7, (int)value);
            }
            else
            {
                SetInt(5, 7, 7, (int)value);
            }
        }
    }

    public int Effect2Amount
    {
        get
        {
            if (_culture == ConquestGameCode.VPYJ)
            {
                return GetInt(4, 14, 8);
            }
            else
            {
                return GetInt(5, 14, 8);
            }
        }
        set
        {
            if (_culture == ConquestGameCode.VPYJ)
            {
                SetInt(4, 14, 8, value);
            }
            else
            {
                SetInt(5, 14, 8, value);
            }
        }
    }

    public WarriorSkillEffectId Effect3
    {
        get
        {
            if (_culture == ConquestGameCode.VPYJ)
            {
                return (WarriorSkillEffectId)GetInt(4, 22, 7);
            }
            else
            {
                return (WarriorSkillEffectId)GetInt(5, 22, 7);
            }
        }
        set
        {
            if (_culture == ConquestGameCode.VPYJ)
            {
                SetInt(4, 22, 7, (int)value);
            }
            else
            {
                SetInt(5, 22, 7, (int)value);
            }
        }
    }

    public int Duration
    {
        get
        {
            if (_culture == ConquestGameCode.VPYJ)
            {
                return GetInt(4, 29, 3);
            }
            else
            {
                return GetInt(5, 29, 3);
            }
        }
        set
        {
            if (_culture == ConquestGameCode.VPYJ)
            {
                SetInt(4, 29, 3, value);
            }
            else
            {
                SetInt(5, 29, 3, value);
            }
        }
    }

    public int Effect3Amount
    {
        get
        {
            if (_culture == ConquestGameCode.VPYJ)
            {
                return GetInt(5, 0, 8);
            }
            else
            {
                return GetInt(6, 0, 8);
            }
        }
        set
        {
            if (_culture == ConquestGameCode.VPYJ)
            {
                SetInt(5, 0, 8, value);
            }
            else
            {
                SetInt(6, 0, 8, value);
            }
        }
    }

    public WarriorSkillTargetId Target
    {
        get
        {
            if (_culture == ConquestGameCode.VPYJ)
            {
                return (WarriorSkillTargetId)GetInt(5, 8, 3);
            }
            else
            {
                return (WarriorSkillTargetId)GetInt(6, 8, 3);
            }
        }
        set
        {
            if (_culture == ConquestGameCode.VPYJ)
            {
                SetInt(5, 8, 3, (int)value);
            }
            else
            {
                SetInt(6, 8, 3, (int)value);
            }
        }
    }

    public MoveAnimationId Animation
    {
        get
        {
            if (_culture == ConquestGameCode.VPYJ)
            {
                return (MoveAnimationId)GetInt(5, 11, 9);
            }
            else
            {
                return (MoveAnimationId)GetInt(6, 11, 9);
            }
        }
        set
        {
            if (_culture == ConquestGameCode.VPYJ)
            {
                SetInt(5, 11, 9, (int)value);
            }
            else
            {
                SetInt(6, 11, 9, (int)value);
            }
        }
    }
}