// This file is automatically generated

#nullable enable

using RanseiLink.Core.Enums;
using RanseiLink.Core.Graphics;
using RanseiLink.Core.Models;

namespace RanseiLink.GuiCore.ViewModels;

public partial class AbilityViewModel : ViewModelBase
{
    private Ability _model = new();
    private AbilityId _id;
    public int Id => (int)_id;

    public string Name
    {
        get => _model.Name;
        set => SetProperty(_model.Name, value, v => _model.Name = v);
    }

    public int Effect1Amount
    {
        get => _model.Effect1Amount;
        set => SetProperty(_model.Effect1Amount, value, v => _model.Effect1Amount = v);
    }

    public AbilityEffectId Effect1
    {
        get => _model.Effect1;
        set => SetProperty(_model.Effect1, value, v => _model.Effect1 = v);
    }

    public AbilityEffectId Effect2
    {
        get => _model.Effect2;
        set => SetProperty(_model.Effect2, value, v => _model.Effect2 = v);
    }

    public int Effect2Amount
    {
        get => _model.Effect2Amount;
        set => SetProperty(_model.Effect2Amount, value, v => _model.Effect2Amount = v);
    }
}