// This file is automatically generated

#nullable enable

using RanseiLink.Core.Enums;
using RanseiLink.Core.Graphics;
using RanseiLink.Core.Models;
using RanseiLink.Core.Services;

namespace RanseiLink.GuiCore.ViewModels;

public partial class BaseWarriorViewModel : ViewModelBase
{
    private BaseWarrior _model = new();
    private WarriorId _id;
    public int Id => (int)_id;


    public int Sprite_Max => 255;
    public int Sprite
    {
        get => _model.Sprite;
        set => SetProperty(_model.Sprite, value, v => _model.Sprite = v);
    }

    public int SpeakerId
    {
        get => (int)_model.SpeakerId;
        set => SetProperty(_model.SpeakerId, (SpeakerId)value, v => _model.SpeakerId = v);
    }

    public GenderId Gender
    {
        get => _model.Gender;
        set => SetProperty(_model.Gender, value, v => _model.Gender = v);
    }

    public int Name_Max => 209;
    public int Name
    {
        get => _model.Name;
        set => SetProperty(_model.Name, value, v => _model.Name = v);
    }

    public TypeId Speciality1
    {
        get => _model.Speciality1;
        set => SetProperty(_model.Speciality1, value, v => _model.Speciality1 = v);
    }

    public TypeId Speciality2
    {
        get => _model.Speciality2;
        set => SetProperty(_model.Speciality2, value, v => _model.Speciality2 = v);
    }

    public TypeId Weakness1
    {
        get => _model.Weakness1;
        set => SetProperty(_model.Weakness1, value, v => _model.Weakness1 = v);
    }

    public TypeId Weakness2
    {
        get => _model.Weakness2;
        set => SetProperty(_model.Weakness2, value, v => _model.Weakness2 = v);
    }

    public int Skill
    {
        get => (int)_model.Skill;
        set => SetProperty(_model.Skill, (WarriorSkillId)value, v => _model.Skill = v);
    }

    public int Power_Max => 127;
    public int Power
    {
        get => _model.Power;
        set => SetProperty(_model.Power, value, v => _model.Power = v);
    }

    public int Wisdom_Max => 127;
    public int Wisdom
    {
        get => _model.Wisdom;
        set => SetProperty(_model.Wisdom, value, v => _model.Wisdom = v);
    }

    public int Charisma_Max => 127;
    public int Charisma
    {
        get => _model.Charisma;
        set => SetProperty(_model.Charisma, value, v => _model.Charisma = v);
    }

    public int Capacity_Max => 8;
    public int Capacity
    {
        get => _model.Capacity;
        set => SetProperty(_model.Capacity, value, v => _model.Capacity = v);
    }

    public RankUpConditionId RankUpCondition1
    {
        get => _model.RankUpCondition1;
        set => SetProperty(_model.RankUpCondition1, value, v => _model.RankUpCondition1 = v);
    }

    public RankUpConditionId RankUpCondition2
    {
        get => _model.RankUpCondition2;
        set => SetProperty(_model.RankUpCondition2, value, v => _model.RankUpCondition2 = v);
    }

    public int Quantity1ForRankUpCondition_Max => 511;
    public int Quantity1ForRankUpCondition
    {
        get => _model.Quantity1ForRankUpCondition;
        set => SetProperty(_model.Quantity1ForRankUpCondition, value, v => _model.Quantity1ForRankUpCondition = v);
    }

    public int Quantity2ForRankUpCondition_Max => 511;
    public int Quantity2ForRankUpCondition
    {
        get => _model.Quantity2ForRankUpCondition;
        set => SetProperty(_model.Quantity2ForRankUpCondition, value, v => _model.Quantity2ForRankUpCondition = v);
    }

    public int RankUp
    {
        get => (int)_model.RankUp;
        set => SetProperty(_model.RankUp, (WarriorId)value, v => _model.RankUp = v);
    }

    public int RankUpPokemon1
    {
        get => (int)_model.RankUpPokemon1;
        set => SetProperty(_model.RankUpPokemon1, (PokemonId)value, v => _model.RankUpPokemon1 = v);
    }

    public int RankUpPokemon2
    {
        get => (int)_model.RankUpPokemon2;
        set => SetProperty(_model.RankUpPokemon2, (PokemonId)value, v => _model.RankUpPokemon2 = v);
    }

    public int RankUpLink_Max => 100;
    public int RankUpLink
    {
        get => _model.RankUpLink;
        set => SetProperty(_model.RankUpLink, value, v => _model.RankUpLink = v);
    }
}