// This file is automatically generated

#nullable enable

using RanseiLink.Core.Enums;
using RanseiLink.Core.Graphics;
using RanseiLink.Core.Models;
using RanseiLink.Core.Services;
using System.Collections.ObjectModel;

namespace RanseiLink.GuiCore.ViewModels;

public partial class BattleConfigViewModel : ViewModelBase
{
    private BattleConfig _model = new();
    private BattleConfigId _id;
    public int Id => (int)_id;


    public int Map_Max => 63;
    public int Map
    {
        get => _model.Map;
        set => SetProperty(_model.Map, value, v => _model.Map = v);
    }

    public int MapVariant_Max => 31;
    public int MapVariant
    {
        get => _model.MapVariant;
        set => SetProperty(_model.MapVariant, value, v => _model.MapVariant = v);
    }

    public int Minimap_Max => 31;
    public int Minimap
    {
        get => _model.Minimap;
        set => SetProperty(_model.Minimap, value, v => _model.Minimap = v);
    }

    public int MinimapVariant_Max => 7;
    public int MinimapVariant
    {
        get => _model.MinimapVariant;
        set => SetProperty(_model.MinimapVariant, value, v => _model.MinimapVariant = v);
    }

    public int Unknown_Max => 63;
    public int Unknown
    {
        get => _model.Unknown;
        set => SetProperty(_model.Unknown, value, v => _model.Unknown = v);
    }

    public Rgb15 UpperAtmosphereColor
    {
        get => _model.UpperAtmosphereColor;
        set => SetProperty(_model.UpperAtmosphereColor, value, v => _model.UpperAtmosphereColor = v);
    }

    public Rgb15 MiddleAtmosphereColor
    {
        get => _model.MiddleAtmosphereColor;
        set => SetProperty(_model.MiddleAtmosphereColor, value, v => _model.MiddleAtmosphereColor = v);
    }

    public Rgb15 LowerAtmosphereColor
    {
        get => _model.LowerAtmosphereColor;
        set => SetProperty(_model.LowerAtmosphereColor, value, v => _model.LowerAtmosphereColor = v);
    }

    public BattleVictoryConditionFlags VictoryCondition
    {
        get => _model.VictoryCondition;
        set => SetProperty(_model.VictoryCondition, value, v => _model.VictoryCondition = v);
    }

    public BattleVictoryConditionFlags DefeatCondition
    {
        get => _model.DefeatCondition;
        set => SetProperty(_model.DefeatCondition, value, v => _model.DefeatCondition = v);
    }

    public int NumberOfTurns_Max => 31;
    public int NumberOfTurns
    {
        get => _model.NumberOfTurns;
        set => SetProperty(_model.NumberOfTurns, value, v => _model.NumberOfTurns = v);
    }

    public int Treasure1
    {
        get => (int)_model.Treasure1;
        set => SetProperty(_model.Treasure1, (ItemId)value, v => _model.Treasure1 = v);
    }

    public int Treasure2
    {
        get => (int)_model.Treasure2;
        set => SetProperty(_model.Treasure2, (ItemId)value, v => _model.Treasure2 = v);
    }

    public int Treasure3
    {
        get => (int)_model.Treasure3;
        set => SetProperty(_model.Treasure3, (ItemId)value, v => _model.Treasure3 = v);
    }

    public int Treasure4
    {
        get => (int)_model.Treasure4;
        set => SetProperty(_model.Treasure4, (ItemId)value, v => _model.Treasure4 = v);
    }

    public int Treasure5
    {
        get => (int)_model.Treasure5;
        set => SetProperty(_model.Treasure5, (ItemId)value, v => _model.Treasure5 = v);
    }

    public int Treasure6
    {
        get => (int)_model.Treasure6;
        set => SetProperty(_model.Treasure6, (ItemId)value, v => _model.Treasure6 = v);
    }

    public int Treasure7
    {
        get => (int)_model.Treasure7;
        set => SetProperty(_model.Treasure7, (ItemId)value, v => _model.Treasure7 = v);
    }

    public int Treasure8
    {
        get => (int)_model.Treasure8;
        set => SetProperty(_model.Treasure8, (ItemId)value, v => _model.Treasure8 = v);
    }

    public int Treasure9
    {
        get => (int)_model.Treasure9;
        set => SetProperty(_model.Treasure9, (ItemId)value, v => _model.Treasure9 = v);
    }

    public int Treasure10
    {
        get => (int)_model.Treasure10;
        set => SetProperty(_model.Treasure10, (ItemId)value, v => _model.Treasure10 = v);
    }

    public int Treasure11
    {
        get => (int)_model.Treasure11;
        set => SetProperty(_model.Treasure11, (ItemId)value, v => _model.Treasure11 = v);
    }

    public int Treasure12
    {
        get => (int)_model.Treasure12;
        set => SetProperty(_model.Treasure12, (ItemId)value, v => _model.Treasure12 = v);
    }

    public List<SelectorComboBoxItem> ItemItems { get; }
}