// This file is automatically generated

#nullable enable

using RanseiLink.Core.Enums;
using RanseiLink.Core.Graphics;

namespace RanseiLink.GuiCore.ViewModels;

public partial class BattleConfigViewModel : ViewModelBase
{
    public int Minimap
    {
        get => _model.Minimap;
        set => SetProperty(_model.Minimap, value, v => _model.Minimap = value);
    }

    public int MinimapVariant
    {
        get => _model.MinimapVariant;
        set => SetProperty(_model.MinimapVariant, value, v => _model.MinimapVariant = value);
    }

    public int Unknown
    {
        get => _model.Unknown;
        set => SetProperty(_model.Unknown, value, v => _model.Unknown = v);
    }

    public int NumberOfTurns
    {
        get => _model.NumberOfTurns;
        set => SetProperty(_model.NumberOfTurns, value, v => _model.NumberOfTurns = v);
    }

    public Rgb15 UpperAtmosphereColor
    {
        get => _model.UpperAtmosphereColor;
        set => SetProperty(_model.UpperAtmosphereColor, value, v => _model.UpperAtmosphereColor = v);
    }

    public Rgb15 MiddleAtmosphereColor
    {
        get => _model.MiddleAtmosphereColor;
        set => SetProperty(_model.MiddleAtmosphereColor, value, v => _model.MiddleAtmosphereColor = v);
    }

    public Rgb15 LowerAtmosphereColor
    {
        get => _model.LowerAtmosphereColor;
        set => SetProperty(_model.LowerAtmosphereColor, value, v => _model.LowerAtmosphereColor = v);
    }
}
