// This file is automatically generated

#nullable enable

using RanseiLink.Core.Enums;
using RanseiLink.Core.Graphics;
using RanseiLink.Core.Models;
using RanseiLink.Core.Services;
using System.Collections.ObjectModel;

namespace RanseiLink.GuiCore.ViewModels;

public partial class BuildingViewModel : ViewModelBase
{
    private Building _model = new(default);
    private BuildingId _id;
    public int Id => (int)_id;


    public int Name_MaxLength => _model.Name_MaxLength;
    public string Name
    {
        get => _model.Name;
        set => SetProperty(_model.Name, value, v => _model.Name = v);
    }

    public int Building1
    {
        get => (int)_model.Building1;
        set => SetProperty(_model.Building1, (BuildingId)value, v => _model.Building1 = v);
    }

    public int Building2
    {
        get => (int)_model.Building2;
        set => SetProperty(_model.Building2, (BuildingId)value, v => _model.Building2 = v);
    }

    public int Building3
    {
        get => (int)_model.Building3;
        set => SetProperty(_model.Building3, (BuildingId)value, v => _model.Building3 = v);
    }

    public int Building4
    {
        get => (int)_model.Building4;
        set => SetProperty(_model.Building4, (BuildingId)value, v => _model.Building4 = v);
    }

    public int Building5
    {
        get => (int)_model.Building5;
        set => SetProperty(_model.Building5, (BuildingId)value, v => _model.Building5 = v);
    }

    public int Building6
    {
        get => (int)_model.Building6;
        set => SetProperty(_model.Building6, (BuildingId)value, v => _model.Building6 = v);
    }

    public int Building7
    {
        get => (int)_model.Building7;
        set => SetProperty(_model.Building7, (BuildingId)value, v => _model.Building7 = v);
    }

    public int Building8
    {
        get => (int)_model.Building8;
        set => SetProperty(_model.Building8, (BuildingId)value, v => _model.Building8 = v);
    }

    public int Kingdom
    {
        get => (int)_model.Kingdom;
        set => SetProperty(_model.Kingdom, (KingdomId)value, v => _model.Kingdom = v);
    }

    public BattleConfigId BattleConfig1
    {
        get => _model.BattleConfig1;
        set => SetProperty(_model.BattleConfig1, value, v => _model.BattleConfig1 = v);
    }

    public BattleConfigId BattleConfig2
    {
        get => _model.BattleConfig2;
        set => SetProperty(_model.BattleConfig2, value, v => _model.BattleConfig2 = v);
    }

    public BattleConfigId BattleConfig3
    {
        get => _model.BattleConfig3;
        set => SetProperty(_model.BattleConfig3, value, v => _model.BattleConfig3 = v);
    }

    public int Sprite1_Max => 127;
    public int Sprite1
    {
        get => _model.Sprite1;
        set => SetProperty(_model.Sprite1, value, v => _model.Sprite1 = v);
    }

    public int Sprite2_Max => 127;
    public int Sprite2
    {
        get => _model.Sprite2;
        set => SetProperty(_model.Sprite2, value, v => _model.Sprite2 = v);
    }

    public int Sprite3_Max => 127;
    public int Sprite3
    {
        get => _model.Sprite3;
        set => SetProperty(_model.Sprite3, value, v => _model.Sprite3 = v);
    }

    public BuildingFunctionId Function
    {
        get => _model.Function;
        set => SetProperty(_model.Function, value, v => _model.Function = v);
    }

    public List<SelectorComboBoxItem> BuildingItems { get; }

    public List<SelectorComboBoxItem> KingdomItems { get; }
}