// This file is automatically generated

#nullable enable

using RanseiLink.Core.Enums;
using RanseiLink.Core.Graphics;
using RanseiLink.Core.Models;

namespace RanseiLink.GuiCore.ViewModels;

public partial class EpisodeViewModel : ViewModelBase
{
    private Episode _model = new();

    public int Order
    {
        get => _model.Order;
        set => SetProperty(_model.Order, value, v => _model.Order = v);
    }

    public ScenarioId Scenario
    {
        get => _model.Scenario;
        set => SetProperty(_model.Scenario, value, v => _model.Scenario = v);
    }

    public int UnlockCondition
    {
        get => (int)_model.UnlockCondition;
        set => SetProperty(_model.UnlockCondition, (EpisodeId)value, v => _model.UnlockCondition = v);
    }

    public int Difficulty
    {
        get => _model.Difficulty;
        set => SetProperty(_model.Difficulty, value, v => _model.Difficulty = v);
    }

    public EpisodeClearConditionId ClearCondition
    {
        get => _model.ClearCondition;
        set => SetProperty(_model.ClearCondition, value, v => _model.ClearCondition = v);
    }


}