// This file is automatically generated

#nullable enable

using RanseiLink.Core.Enums;
using RanseiLink.Core.Graphics;
using RanseiLink.Core.Models;
using RanseiLink.Core.Services;

namespace RanseiLink.GuiCore.ViewModels;

public partial class EpisodeViewModel : ViewModelBase
{
    private Episode _model = new();
    private EpisodeId _id;
    public int Id => (int)_id;


    public int Order_Max => 511;
    public int Order
    {
        get => _model.Order;
        set => SetProperty(_model.Order, value, v => _model.Order = v);
    }

    public ScenarioId Scenario
    {
        get => _model.Scenario;
        set => SetProperty(_model.Scenario, value, v => _model.Scenario = v);
    }

    public int UnlockCondition
    {
        get => (int)_model.UnlockCondition;
        set => SetProperty(_model.UnlockCondition, (EpisodeId)value, v => _model.UnlockCondition = v);
    }

    public int Difficulty_Max => 4;
    public int Difficulty
    {
        get => _model.Difficulty;
        set => SetProperty(_model.Difficulty, value, v => _model.Difficulty = v);
    }

    public EpisodeClearConditionId ClearCondition
    {
        get => _model.ClearCondition;
        set => SetProperty(_model.ClearCondition, value, v => _model.ClearCondition = v);
    }

    public string Name
    {
        get => _msgService.GetMsgOfType(MsgShortcut.EpisodeName, Id);
        set => _msgService.SetMsgOfType(MsgShortcut.EpisodeName, Id, value);
    }

    public string Description
    {
        get => _msgService.GetMsgOfType(MsgShortcut.EpisodeDescription, Id);
        set => _msgService.SetMsgOfType(MsgShortcut.EpisodeDescription, Id, value);
    }
}