// This file is automatically generated

#nullable enable

using RanseiLink.Core.Enums;
using RanseiLink.Core.Graphics;
using RanseiLink.Core.Models;
using RanseiLink.Core.Services;
using System.Collections.ObjectModel;

namespace RanseiLink.GuiCore.ViewModels;

public partial class EventSpeakerViewModel : ViewModelBase
{
    private EventSpeaker _model = new(default);
    private EventSpeakerId _id;
    public int Id => (int)_id;


    public int Name_MaxLength => _model.Name_MaxLength;
    public string Name
    {
        get => _model.Name;
        set => SetProperty(_model.Name, value, v => _model.Name = v);
    }

    public int Sprite_Max => 255;
    public int Sprite
    {
        get => _model.Sprite;
        set => SetProperty(_model.Sprite, value, v => _model.Sprite = v);
    }
}