// This file is automatically generated

#nullable enable

using RanseiLink.Core.Enums;
using RanseiLink.Core.Graphics;
using RanseiLink.Core.Models;
using RanseiLink.Core.Services;
using System.Collections.ObjectModel;

namespace RanseiLink.GuiCore.ViewModels;

public partial class GimmickViewModel : ViewModelBase
{
    private Gimmick _model = new(default);
    private GimmickId _id;
    public int Id => (int)_id;


    public int Name_MaxLength => _model.Name_MaxLength;
    public string Name
    {
        get => _model.Name;
        set => SetProperty(_model.Name, value, v => _model.Name = v);
    }

    public int Image_Max => 255;
    public int Image
    {
        get => _model.Image;
        set => SetProperty(_model.Image, value, v => _model.Image = v);
    }

    public TypeId AttackType
    {
        get => _model.AttackType;
        set => SetProperty(_model.AttackType, value, v => _model.AttackType = v);
    }

    public TypeId DestroyType
    {
        get => _model.DestroyType;
        set => SetProperty(_model.DestroyType, value, v => _model.DestroyType = v);
    }

    public GimmickObjectId State1Sprite
    {
        get => _model.State1Sprite;
        set => SetProperty(_model.State1Sprite, value, v => _model.State1Sprite = v);
    }

    public GimmickObjectId State2Sprite
    {
        get => _model.State2Sprite;
        set => SetProperty(_model.State2Sprite, value, v => _model.State2Sprite = v);
    }

    public MoveEffectId Effect
    {
        get => _model.Effect;
        set => SetProperty(_model.Effect, value, v => _model.Effect = v);
    }

    public int UnknownQuantity1_Max => 255;
    public int UnknownQuantity1
    {
        get => _model.UnknownQuantity1;
        set => SetProperty(_model.UnknownQuantity1, value, v => _model.UnknownQuantity1 = v);
    }

    public MoveAnimationId Animation1
    {
        get => _model.Animation1;
        set => SetProperty(_model.Animation1, value, v => _model.Animation1 = v);
    }

    public MoveAnimationId Animation2
    {
        get => _model.Animation2;
        set => SetProperty(_model.Animation2, value, v => _model.Animation2 = v);
    }

    public GimmickRangeId Range
    {
        get => _model.Range;
        set => SetProperty(_model.Range, value, v => _model.Range = v);
    }
}