// This file is automatically generated

#nullable enable

using RanseiLink.Core.Enums;
using RanseiLink.Core.Graphics;
using RanseiLink.Core.Models;
using RanseiLink.Core.Services;
using System.Collections.ObjectModel;

namespace RanseiLink.GuiCore.ViewModels;

public partial class GimmickViewModel : ViewModelBase
{
    private Gimmick _model = new(default);
    private GimmickId _id;
    public int Id => (int)_id;


    public int Name_MaxLength => _model.Name_MaxLength;
    public string Name
    {
        get => _model.Name;
        set => SetProperty(_model.Name, value, v => _model.Name = v);
    }

    public int Image1_Max => 255;
    public int Image1
    {
        get => _model.Image1;
        set => SetProperty(_model.Image1, value, v => _model.Image1 = v);
    }

    public TypeId AttackType
    {
        get => _model.AttackType;
        set => SetProperty(_model.AttackType, value, v => _model.AttackType = v);
    }

    public TypeId DestroyType
    {
        get => _model.DestroyType;
        set => SetProperty(_model.DestroyType, value, v => _model.DestroyType = v);
    }

    public bool IsLog
    {
        get => _model.IsLog;
        set => SetProperty(_model.IsLog, value, v => _model.IsLog = v);
    }

    public int State1Sprite
    {
        get => (int)_model.State1Sprite;
        set => SetProperty(_model.State1Sprite, (GimmickObjectId)value, v => _model.State1Sprite = v);
    }

    public int State2Sprite
    {
        get => (int)_model.State2Sprite;
        set => SetProperty(_model.State2Sprite, (GimmickObjectId)value, v => _model.State2Sprite = v);
    }

    public MoveEffectId Effect
    {
        get => _model.Effect;
        set => SetProperty(_model.Effect, value, v => _model.Effect = v);
    }

    public int AttackPower_Max => 255;
    public int AttackPower
    {
        get => _model.AttackPower;
        set => SetProperty(_model.AttackPower, value, v => _model.AttackPower = v);
    }

    public int Anim1_Max => 255;
    public int Anim1
    {
        get => _model.Anim1;
        set => SetProperty(_model.Anim1, value, v => _model.Anim1 = v);
    }

    public int Anim2_Max => 255;
    public int Anim2
    {
        get => _model.Anim2;
        set => SetProperty(_model.Anim2, value, v => _model.Anim2 = v);
    }

    public int GimmickRef1
    {
        get => (int)_model.GimmickRef1;
        set => SetProperty(_model.GimmickRef1, (GimmickId)value, v => _model.GimmickRef1 = v);
    }

    public int Unknown_7_0_5_Max => 31;
    public int Unknown_7_0_5
    {
        get => _model.Unknown_7_0_5;
        set => SetProperty(_model.Unknown_7_0_5, value, v => _model.Unknown_7_0_5 = v);
    }

    public int Unknown_7_5_5_Max => 31;
    public int Unknown_7_5_5
    {
        get => _model.Unknown_7_5_5;
        set => SetProperty(_model.Unknown_7_5_5, value, v => _model.Unknown_7_5_5 = v);
    }

    public int Unknown_7_10_5_Max => 31;
    public int Unknown_7_10_5
    {
        get => _model.Unknown_7_10_5;
        set => SetProperty(_model.Unknown_7_10_5, value, v => _model.Unknown_7_10_5 = v);
    }

    public int Unknown_7_15_5_Max => 31;
    public int Unknown_7_15_5
    {
        get => _model.Unknown_7_15_5;
        set => SetProperty(_model.Unknown_7_15_5, value, v => _model.Unknown_7_15_5 = v);
    }

    public int Unknown_7_20_12_Max => 4095;
    public int Unknown_7_20_12
    {
        get => _model.Unknown_7_20_12;
        set => SetProperty(_model.Unknown_7_20_12, value, v => _model.Unknown_7_20_12 = v);
    }

    public int Unknown_8_0_8_Max => 255;
    public int Unknown_8_0_8
    {
        get => _model.Unknown_8_0_8;
        set => SetProperty(_model.Unknown_8_0_8, value, v => _model.Unknown_8_0_8 = v);
    }

    public int Unknown_8_8_8_Max => 255;
    public int Unknown_8_8_8
    {
        get => _model.Unknown_8_8_8;
        set => SetProperty(_model.Unknown_8_8_8, value, v => _model.Unknown_8_8_8 = v);
    }

    public int Unknown_8_16_3_Max => 7;
    public int Unknown_8_16_3
    {
        get => _model.Unknown_8_16_3;
        set => SetProperty(_model.Unknown_8_16_3, value, v => _model.Unknown_8_16_3 = v);
    }

    public int Unknown_8_24_3_Max => 7;
    public int Unknown_8_24_3
    {
        get => _model.Unknown_8_24_3;
        set => SetProperty(_model.Unknown_8_24_3, value, v => _model.Unknown_8_24_3 = v);
    }

    public int Unknown_9_0_4_Max => 15;
    public int Unknown_9_0_4
    {
        get => _model.Unknown_9_0_4;
        set => SetProperty(_model.Unknown_9_0_4, value, v => _model.Unknown_9_0_4 = v);
    }

    public int GimmickRef2
    {
        get => (int)_model.GimmickRef2;
        set => SetProperty(_model.GimmickRef2, (GimmickId)value, v => _model.GimmickRef2 = v);
    }

    public int Image2_Max => 255;
    public int Image2
    {
        get => _model.Image2;
        set => SetProperty(_model.Image2, value, v => _model.Image2 = v);
    }

    public int Image3_Max => 255;
    public int Image3
    {
        get => _model.Image3;
        set => SetProperty(_model.Image3, value, v => _model.Image3 = v);
    }

    public int Range
    {
        get => (int)_model.Range;
        set => SetProperty(_model.Range, (GimmickRangeId)value, v => _model.Range = v);
    }

    public List<SelectorComboBoxItem> GimmickObjectItems { get; }

    public List<SelectorComboBoxItem> GimmickItems { get; }

    public List<SelectorComboBoxItem> GimmickRangeItems { get; }
}