// This file is automatically generated

#nullable enable

using RanseiLink.Core.Enums;
using RanseiLink.Core.Graphics;
using RanseiLink.Core.Models;
using RanseiLink.Core.Services;
using System.Collections.ObjectModel;

namespace RanseiLink.GuiCore.ViewModels;

public partial class ItemViewModel : ViewModelBase
{
    private Item _model = new();
    private ItemId _id;
    public int Id => (int)_id;


    public int Name_MaxLength => _model.Name_MaxLength;
    public string Name
    {
        get => _model.Name;
        set => SetProperty(_model.Name, value, v => _model.Name = v);
    }

    public int Unknown_5_8_1_Max => 1;
    public int Unknown_5_8_1
    {
        get => _model.Unknown_5_8_1;
        set => SetProperty(_model.Unknown_5_8_1, value, v => _model.Unknown_5_8_1 = v);
    }

    public int Unknown_5_9_5_Max => 31;
    public int Unknown_5_9_5
    {
        get => _model.Unknown_5_9_5;
        set => SetProperty(_model.Unknown_5_9_5, value, v => _model.Unknown_5_9_5 = v);
    }

    public int Unknown_5_14_2_Max => 3;
    public int Unknown_5_14_2
    {
        get => _model.Unknown_5_14_2;
        set => SetProperty(_model.Unknown_5_14_2, value, v => _model.Unknown_5_14_2 = v);
    }

    public PurchaseMethodId PurchaseMethod
    {
        get => _model.PurchaseMethod;
        set => SetProperty(_model.PurchaseMethod, value, v => _model.PurchaseMethod = v);
    }

    public ItemCategoryId Category
    {
        get => _model.Category;
        set => SetProperty(_model.Category, value, v => _model.Category = v);
    }

    public ItemEffectId Effect
    {
        get => _model.Effect;
        set => SetProperty(_model.Effect, value, v => _model.Effect = v);
    }

    public int EffectDuration_Max => 31;
    public int EffectDuration
    {
        get => _model.EffectDuration;
        set => SetProperty(_model.EffectDuration, value, v => _model.EffectDuration = v);
    }

    public int Unknown_5_31_1_Max => 1;
    public int Unknown_5_31_1
    {
        get => _model.Unknown_5_31_1;
        set => SetProperty(_model.Unknown_5_31_1, value, v => _model.Unknown_5_31_1 = v);
    }

    public int CraftingIngredient1
    {
        get => (int)_model.CraftingIngredient1;
        set => SetProperty(_model.CraftingIngredient1, (ItemId)value, v => _model.CraftingIngredient1 = v);
    }

    public int CraftingIngredient1Amount_Max => 127;
    public int CraftingIngredient1Amount
    {
        get => _model.CraftingIngredient1Amount;
        set => SetProperty(_model.CraftingIngredient1Amount, value, v => _model.CraftingIngredient1Amount = v);
    }

    public int CraftingIngredient2
    {
        get => (int)_model.CraftingIngredient2;
        set => SetProperty(_model.CraftingIngredient2, (ItemId)value, v => _model.CraftingIngredient2 = v);
    }

    public int CraftingIngredient2Amount_Max => 127;
    public int CraftingIngredient2Amount
    {
        get => _model.CraftingIngredient2Amount;
        set => SetProperty(_model.CraftingIngredient2Amount, value, v => _model.CraftingIngredient2Amount = v);
    }

    public int UnknownItem
    {
        get => (int)_model.UnknownItem;
        set => SetProperty(_model.UnknownItem, (ItemId)value, v => _model.UnknownItem = v);
    }

    public int ShopPriceMultiplier_Max => 511;
    public int ShopPriceMultiplier
    {
        get => _model.ShopPriceMultiplier;
        set => SetProperty(_model.ShopPriceMultiplier, value, v => _model.ShopPriceMultiplier = v);
    }

    public int Effect_Quantity_Max => 511;
    public int Effect_Quantity
    {
        get => _model.Effect_Quantity;
        set => SetProperty(_model.Effect_Quantity, value, v => _model.Effect_Quantity = v);
    }

    public int EffectModifier_Max => 511;
    public int EffectModifier
    {
        get => _model.EffectModifier;
        set => SetProperty(_model.EffectModifier, value, v => _model.EffectModifier = v);
    }

    public ObservableCollection<CheckBoxViewModel> PurchasableItems { get; } = [];

    public string Description
    {
        get => _msgService.GetMsgOfType(MsgShortcut.ItemDescription, Id);
        set
        {
            _msgService.SetMsgOfType(MsgShortcut.ItemDescription, Id, value);
            RaisePropertyChanged();
        }
    }

    public string Description2
    {
        get => _msgService.GetMsgOfType(MsgShortcut.ItemDescription2, Id);
        set
        {
            _msgService.SetMsgOfType(MsgShortcut.ItemDescription2, Id, value);
            RaisePropertyChanged();
        }
    }

    public List<SelectorComboBoxItem> ItemItems { get; }
}