// This file is automatically generated

#nullable enable

using RanseiLink.Core.Enums;
using RanseiLink.Core.Graphics;
using RanseiLink.Core.Models;
using RanseiLink.Core.Services;
using System.Collections.ObjectModel;

namespace RanseiLink.GuiCore.ViewModels;

public partial class KingdomViewModel : ViewModelBase
{
    private Kingdom _model = new(default);
    private KingdomId _id;
    public int Id => (int)_id;


    public int Name_MaxLength => _model.Name_MaxLength;
    public string Name
    {
        get => _model.Name;
        set => SetProperty(_model.Name, value, v => _model.Name = v);
    }

    public int Unknown_2_24_3_Max => 7;
    public int Unknown_2_24_3
    {
        get => _model.Unknown_2_24_3;
        set => SetProperty(_model.Unknown_2_24_3, value, v => _model.Unknown_2_24_3 = v);
    }

    public int MapConnection0
    {
        get => (int)_model.MapConnection0;
        set => SetProperty(_model.MapConnection0, (KingdomId)value, v => _model.MapConnection0 = v);
    }

    public int MapConnection1
    {
        get => (int)_model.MapConnection1;
        set => SetProperty(_model.MapConnection1, (KingdomId)value, v => _model.MapConnection1 = v);
    }

    public int MapConnection2
    {
        get => (int)_model.MapConnection2;
        set => SetProperty(_model.MapConnection2, (KingdomId)value, v => _model.MapConnection2 = v);
    }

    public int MapConnection4
    {
        get => (int)_model.MapConnection4;
        set => SetProperty(_model.MapConnection4, (KingdomId)value, v => _model.MapConnection4 = v);
    }

    public int MapConnection3
    {
        get => (int)_model.MapConnection3;
        set => SetProperty(_model.MapConnection3, (KingdomId)value, v => _model.MapConnection3 = v);
    }

    public int MapConnection5
    {
        get => (int)_model.MapConnection5;
        set => SetProperty(_model.MapConnection5, (KingdomId)value, v => _model.MapConnection5 = v);
    }

    public int MapConnection6
    {
        get => (int)_model.MapConnection6;
        set => SetProperty(_model.MapConnection6, (KingdomId)value, v => _model.MapConnection6 = v);
    }

    public int MapConnection7
    {
        get => (int)_model.MapConnection7;
        set => SetProperty(_model.MapConnection7, (KingdomId)value, v => _model.MapConnection7 = v);
    }

    public int MapConnection8
    {
        get => (int)_model.MapConnection8;
        set => SetProperty(_model.MapConnection8, (KingdomId)value, v => _model.MapConnection8 = v);
    }

    public int MapConnection9
    {
        get => (int)_model.MapConnection9;
        set => SetProperty(_model.MapConnection9, (KingdomId)value, v => _model.MapConnection9 = v);
    }

    public int MapConnection10
    {
        get => (int)_model.MapConnection10;
        set => SetProperty(_model.MapConnection10, (KingdomId)value, v => _model.MapConnection10 = v);
    }

    public int MapConnection11
    {
        get => (int)_model.MapConnection11;
        set => SetProperty(_model.MapConnection11, (KingdomId)value, v => _model.MapConnection11 = v);
    }

    public int MapConnection12
    {
        get => (int)_model.MapConnection12;
        set => SetProperty(_model.MapConnection12, (KingdomId)value, v => _model.MapConnection12 = v);
    }

    public int BattleConfig
    {
        get => (int)_model.BattleConfig;
        set => SetProperty(_model.BattleConfig, (BattleConfigId)value, v => _model.BattleConfig = v);
    }

    public int SwarmPokemon
    {
        get => (int)_model.SwarmPokemon;
        set => SetProperty(_model.SwarmPokemon, (PokemonId)value, v => _model.SwarmPokemon = v);
    }

    public List<SelectorComboBoxItem> KingdomItems { get; }

    public List<SelectorComboBoxItem> BattleConfigItems { get; }

    public List<SelectorComboBoxItem> PokemonItems { get; }
}