// This file is automatically generated

#nullable enable

using RanseiLink.Core.Enums;
using RanseiLink.Core.Graphics;
using RanseiLink.Core.Models;
using RanseiLink.Core.Services;
using System.Collections.ObjectModel;

namespace RanseiLink.GuiCore.ViewModels;

public partial class MapPointViewModel : ViewModelBase
{
    private MapPoint _model = new();
    private MapPointId _id;
    public int Id => (int)_id;


    public int Gimmick
    {
        get => (int)_model.Gimmick;
        set => SetProperty(_model.Gimmick, (GimmickId)value, v => _model.Gimmick = v);
    }

    public int Cell_Max => 511;
    public int Cell
    {
        get => _model.Cell;
        set => SetProperty(_model.Cell, value, v => _model.Cell = v);
    }

    public int Unknown_0_17_2_Max => 3;
    public int Unknown_0_17_2
    {
        get => _model.Unknown_0_17_2;
        set => SetProperty(_model.Unknown_0_17_2, value, v => _model.Unknown_0_17_2 = v);
    }

    public int Unknown_0_19_1_Max => 1;
    public int Unknown_0_19_1
    {
        get => _model.Unknown_0_19_1;
        set => SetProperty(_model.Unknown_0_19_1, value, v => _model.Unknown_0_19_1 = v);
    }

    public int Unknown_0_20_1_Max => 1;
    public int Unknown_0_20_1
    {
        get => _model.Unknown_0_20_1;
        set => SetProperty(_model.Unknown_0_20_1, value, v => _model.Unknown_0_20_1 = v);
    }

    public int Unknown_0_21_5_Max => 31;
    public int Unknown_0_21_5
    {
        get => _model.Unknown_0_21_5;
        set => SetProperty(_model.Unknown_0_21_5, value, v => _model.Unknown_0_21_5 = v);
    }

    public int Unknown_0_26_6_Max => 63;
    public int Unknown_0_26_6
    {
        get => _model.Unknown_0_26_6;
        set => SetProperty(_model.Unknown_0_26_6, value, v => _model.Unknown_0_26_6 = v);
    }

    public int Unknown_1_0_8_Max => 255;
    public int Unknown_1_0_8
    {
        get => _model.Unknown_1_0_8;
        set => SetProperty(_model.Unknown_1_0_8, value, v => _model.Unknown_1_0_8 = v);
    }

    public int Unknown_1_8_9_Max => 511;
    public int Unknown_1_8_9
    {
        get => _model.Unknown_1_8_9;
        set => SetProperty(_model.Unknown_1_8_9, value, v => _model.Unknown_1_8_9 = v);
    }

    public int Unknown_1_17_7_Max => 127;
    public int Unknown_1_17_7
    {
        get => _model.Unknown_1_17_7;
        set => SetProperty(_model.Unknown_1_17_7, value, v => _model.Unknown_1_17_7 = v);
    }

    public int Unknown_1_24_3_Max => 7;
    public int Unknown_1_24_3
    {
        get => _model.Unknown_1_24_3;
        set => SetProperty(_model.Unknown_1_24_3, value, v => _model.Unknown_1_24_3 = v);
    }

    public int Unknown_1_27_4_Max => 15;
    public int Unknown_1_27_4
    {
        get => _model.Unknown_1_27_4;
        set => SetProperty(_model.Unknown_1_27_4, value, v => _model.Unknown_1_27_4 = v);
    }

    public int Unknown_1_31_1_Max => 1;
    public int Unknown_1_31_1
    {
        get => _model.Unknown_1_31_1;
        set => SetProperty(_model.Unknown_1_31_1, value, v => _model.Unknown_1_31_1 = v);
    }

    public List<SelectorComboBoxItem> GimmickItems { get; }
}