// This file is automatically generated

#nullable enable

using RanseiLink.Core.Enums;
using RanseiLink.Core.Graphics;
using RanseiLink.Core.Models;
using RanseiLink.Core.Services;
using System.Collections.ObjectModel;

namespace RanseiLink.GuiCore.ViewModels;

public partial class MoveViewModel : ViewModelBase
{
    private Move _model = new();
    private MoveId _id;
    public int Id => (int)_id;


    public int Name_MaxLength => _model.Name_MaxLength;
    public string Name
    {
        get => _model.Name;
        set => SetProperty(_model.Name, value, v => _model.Name = v);
    }

    public MoveMovementFlags MovementFlags
    {
        get => _model.MovementFlags;
        set => SetProperty(_model.MovementFlags, value, v => _model.MovementFlags = v);
    }

    public TypeId Type
    {
        get => _model.Type;
        set => SetProperty(_model.Type, value, v => _model.Type = v);
    }

    public int Power_Max => 255;
    public int Power
    {
        get => _model.Power;
        set => SetProperty(_model.Power, value, v => _model.Power = v);
    }

    public MoveEffectId Effect1
    {
        get => _model.Effect1;
        set => SetProperty(_model.Effect1, value, v => _model.Effect1 = v);
    }

    public int Effect1_Quantity_Max => 127;
    public int Effect1_Quantity
    {
        get => _model.Effect1_Quantity;
        set => SetProperty(_model.Effect1_Quantity, value, v => _model.Effect1_Quantity = v);
    }

    public int Range
    {
        get => (int)_model.Range;
        set => SetProperty(_model.Range, (MoveRangeId)value, v => _model.Range = v);
    }

    public int StartupAnimation
    {
        get => (int)_model.StartupAnimation;
        set => SetProperty(_model.StartupAnimation, (MoveAnimationId)value, v => _model.StartupAnimation = v);
    }

    public int ProjectileAnimation
    {
        get => (int)_model.ProjectileAnimation;
        set => SetProperty(_model.ProjectileAnimation, (MoveAnimationId)value, v => _model.ProjectileAnimation = v);
    }

    public int ImpactAnimation
    {
        get => (int)_model.ImpactAnimation;
        set => SetProperty(_model.ImpactAnimation, (MoveAnimationId)value, v => _model.ImpactAnimation = v);
    }

    public MoveEffectId Effect2
    {
        get => _model.Effect2;
        set => SetProperty(_model.Effect2, value, v => _model.Effect2 = v);
    }

    public int Effect2_Quantity_Max => 127;
    public int Effect2_Quantity
    {
        get => _model.Effect2_Quantity;
        set => SetProperty(_model.Effect2_Quantity, value, v => _model.Effect2_Quantity = v);
    }

    public MoveEffectId Rank5Effect1
    {
        get => _model.Rank5Effect1;
        set => SetProperty(_model.Rank5Effect1, value, v => _model.Rank5Effect1 = v);
    }

    public int Rank5Effect1_Quantity_Max => 127;
    public int Rank5Effect1_Quantity
    {
        get => _model.Rank5Effect1_Quantity;
        set => SetProperty(_model.Rank5Effect1_Quantity, value, v => _model.Rank5Effect1_Quantity = v);
    }

    public MoveMovementAnimationTimingId MovementTiming
    {
        get => _model.MovementTiming;
        set => SetProperty(_model.MovementTiming, value, v => _model.MovementTiming = v);
    }

    public MoveEffectId Rank5Effect2
    {
        get => _model.Rank5Effect2;
        set => SetProperty(_model.Rank5Effect2, value, v => _model.Rank5Effect2 = v);
    }

    public int Rank5Effect2_Quantity_Max => 127;
    public int Rank5Effect2_Quantity
    {
        get => _model.Rank5Effect2_Quantity;
        set => SetProperty(_model.Rank5Effect2_Quantity, value, v => _model.Rank5Effect2_Quantity = v);
    }

    public MoveMovementAnimationId MovementAnimation
    {
        get => _model.MovementAnimation;
        set => SetProperty(_model.MovementAnimation, value, v => _model.MovementAnimation = v);
    }

    public int Accuracy_Max => 127;
    public int Accuracy
    {
        get => _model.Accuracy;
        set => SetProperty(_model.Accuracy, value, v => _model.Accuracy = v);
    }

    public MoveInteractionId Interaction
    {
        get => _model.Interaction;
        set => SetProperty(_model.Interaction, value, v => _model.Interaction = v);
    }

    public MoveMovementId Movement
    {
        get => _model.Movement;
        set => SetProperty(_model.Movement, value, v => _model.Movement = v);
    }

    public int AdditionalAnimation
    {
        get => (int)_model.AdditionalAnimation;
        set => SetProperty(_model.AdditionalAnimation, (MoveAnimationId)value, v => _model.AdditionalAnimation = v);
    }

    public int Unknown_8_9_5_Max => 31;
    public int Unknown_8_9_5
    {
        get => _model.Unknown_8_9_5;
        set => SetProperty(_model.Unknown_8_9_5, value, v => _model.Unknown_8_9_5 = v);
    }

    public int Unknown_8_14_6_Max => 63;
    public int Unknown_8_14_6
    {
        get => _model.Unknown_8_14_6;
        set => SetProperty(_model.Unknown_8_14_6, value, v => _model.Unknown_8_14_6 = v);
    }

    public string Description
    {
        get => _msgService.GetMsgOfType(MsgShortcut.MoveDescription, Id);
        set
        {
            _msgService.SetMsgOfType(MsgShortcut.MoveDescription, Id, value);
            RaisePropertyChanged();
        }
    }

    public List<SelectorComboBoxItem> MoveRangeItems { get; }

    public List<SelectorComboBoxItem> MoveAnimationItems { get; }
}