// This file is automatically generated

#nullable enable

using RanseiLink.Core.Enums;
using RanseiLink.Core.Graphics;
using RanseiLink.Core.Models;

namespace RanseiLink.GuiCore.ViewModels;

public partial class MoveViewModel : ViewModelBase
{
    private Move _model = new();

    public string Name
    {
        get => _model.Name;
        set => SetProperty(_model.Name, value, v => _model.Name = v);
    }

    public MoveMovementFlags MovementFlags
    {
        get => _model.MovementFlags;
        set => SetProperty(_model.MovementFlags, value, v => _model.MovementFlags = v);
    }

    public TypeId Type
    {
        get => _model.Type;
        set => SetProperty(_model.Type, value, v => _model.Type = v);
    }

    public int Power
    {
        get => _model.Power;
        set => SetProperty(_model.Power, value, v => _model.Power = v);
    }

    public MoveEffectId Effect1
    {
        get => _model.Effect1;
        set => SetProperty(_model.Effect1, value, v => _model.Effect1 = v);
    }

    public int Effect1Chance
    {
        get => _model.Effect1Chance;
        set => SetProperty(_model.Effect1Chance, value, v => _model.Effect1Chance = v);
    }

    public MoveRangeId Range
    {
        get => _model.Range;
        set => SetProperty(_model.Range, value, v => _model.Range = v);
    }

    public MoveEffectId Effect2
    {
        get => _model.Effect2;
        set => SetProperty(_model.Effect2, value, v => _model.Effect2 = v);
    }

    public int Effect2Chance
    {
        get => _model.Effect2Chance;
        set => SetProperty(_model.Effect2Chance, value, v => _model.Effect2Chance = v);
    }

    public MoveEffectId Effect3
    {
        get => _model.Effect3;
        set => SetProperty(_model.Effect3, value, v => _model.Effect3 = v);
    }

    public int Effect3Chance
    {
        get => _model.Effect3Chance;
        set => SetProperty(_model.Effect3Chance, value, v => _model.Effect3Chance = v);
    }

    public MoveEffectId Effect4
    {
        get => _model.Effect4;
        set => SetProperty(_model.Effect4, value, v => _model.Effect4 = v);
    }

    public int Effect4Chance
    {
        get => _model.Effect4Chance;
        set => SetProperty(_model.Effect4Chance, value, v => _model.Effect4Chance = v);
    }

    public int Accuracy
    {
        get => _model.Accuracy;
        set => SetProperty(_model.Accuracy, value, v => _model.Accuracy = v);
    }

    public MoveAnimationId StartupAnimation
    {
        get => _model.StartupAnimation;
        set => SetProperty(_model.StartupAnimation, value, v => _model.StartupAnimation = v);
    }

    public MoveAnimationId ProjectileAnimation
    {
        get => _model.ProjectileAnimation;
        set => SetProperty(_model.ProjectileAnimation, value, v => _model.ProjectileAnimation = v);
    }

    public MoveAnimationId ImpactAnimation
    {
        get => _model.ImpactAnimation;
        set => SetProperty(_model.ImpactAnimation, value, v => _model.ImpactAnimation = v);
    }

    public MoveAnimationId AdditionalAnimation
    {
        get => _model.AdditionalAnimation;
        set => SetProperty(_model.AdditionalAnimation, value, v => _model.AdditionalAnimation = v);
    }

    public MoveUnknownOptionId UnknownOption
    {
        get => _model.UnknownOption;
        set => SetProperty(_model.UnknownOption, value, v => _model.UnknownOption = v);
    }

    public MoveMovementId Movement
    {
        get => _model.Movement;
        set => SetProperty(_model.Movement, value, v => _model.Movement = v);
    }

    public MoveMovementAnimationId MovementAnimation
    {
        get => _model.MovementAnimation;
        set => SetProperty(_model.MovementAnimation, value, v => _model.MovementAnimation = v);
    }

    public int UnknownValue_6_28_4
    {
        get => _model.UnknownValue_6_28_4;
        set => SetProperty(_model.UnknownValue_6_28_4, value, v => _model.UnknownValue_6_28_4 = v);
    }
}