// This file is automatically generated

#nullable enable

using RanseiLink.Core.Enums;
using RanseiLink.Core.Graphics;
using RanseiLink.Core.Models;
using RanseiLink.Core.Services;

namespace RanseiLink.GuiCore.ViewModels;

public partial class PokemonViewModel : ViewModelBase
{
    private Pokemon _model = new();
    private PokemonId _id;
    public int Id => (int)_id;


    public string Name
    {
        get => _model.Name;
        set => SetProperty(_model.Name, value, v => _model.Name = v);
    }

    public int Hp_Max => 511;
    public int Hp
    {
        get => _model.Hp;
        set => SetProperty(_model.Hp, value, v => _model.Hp = v);
    }

    public EvolutionConditionId EvolutionCondition1
    {
        get => _model.EvolutionCondition1;
        set => SetProperty(_model.EvolutionCondition1, value, v => _model.EvolutionCondition1 = v);
    }

    public EvolutionConditionId EvolutionCondition2
    {
        get => _model.EvolutionCondition2;
        set => SetProperty(_model.EvolutionCondition2, value, v => _model.EvolutionCondition2 = v);
    }

    public IdleMotionId IdleMotion
    {
        get => _model.IdleMotion;
        set => SetProperty(_model.IdleMotion, value, v => _model.IdleMotion = v);
    }

    public int Atk_Max => 511;
    public int Atk
    {
        get => _model.Atk;
        set => SetProperty(_model.Atk, value, v => _model.Atk = v);
    }

    public int Def_Max => 511;
    public int Def
    {
        get => _model.Def;
        set => SetProperty(_model.Def, value, v => _model.Def = v);
    }

    public int Spe_Max => 511;
    public int Spe
    {
        get => _model.Spe;
        set => SetProperty(_model.Spe, value, v => _model.Spe = v);
    }

    public bool IsLegendary
    {
        get => _model.IsLegendary;
        set => SetProperty(_model.IsLegendary, value, v => _model.IsLegendary = v);
    }

    public bool AsymmetricBattleSprite
    {
        get => _model.AsymmetricBattleSprite;
        set => SetProperty(_model.AsymmetricBattleSprite, value, v => _model.AsymmetricBattleSprite = v);
    }

    public bool LongAttackAnimation
    {
        get => _model.LongAttackAnimation;
        set => SetProperty(_model.LongAttackAnimation, value, v => _model.LongAttackAnimation = v);
    }

    public TypeId Type1
    {
        get => _model.Type1;
        set => SetProperty(_model.Type1, value, v => _model.Type1 = v);
    }

    public TypeId Type2
    {
        get => _model.Type2;
        set => SetProperty(_model.Type2, value, v => _model.Type2 = v);
    }

    public int Move
    {
        get => (int)_model.Move;
        set => SetProperty(_model.Move, (MoveId)value, v => _model.Move = v);
    }

    public int Ability1
    {
        get => (int)_model.Ability1;
        set => SetProperty(_model.Ability1, (AbilityId)value, v => _model.Ability1 = v);
    }

    public int Ability2
    {
        get => (int)_model.Ability2;
        set => SetProperty(_model.Ability2, (AbilityId)value, v => _model.Ability2 = v);
    }

    public int Ability3
    {
        get => (int)_model.Ability3;
        set => SetProperty(_model.Ability3, (AbilityId)value, v => _model.Ability3 = v);
    }

    public int QuantityForEvolutionCondition1_Max => 511;
    public int QuantityForEvolutionCondition1
    {
        get => _model.QuantityForEvolutionCondition1;
        set => SetProperty(_model.QuantityForEvolutionCondition1, value, v => _model.QuantityForEvolutionCondition1 = v);
    }

    public int QuantityForEvolutionCondition2_Max => 511;
    public int QuantityForEvolutionCondition2
    {
        get => _model.QuantityForEvolutionCondition2;
        set => SetProperty(_model.QuantityForEvolutionCondition2, value, v => _model.QuantityForEvolutionCondition2 = v);
    }

    public int MovementRange_Max => 7;
    public int MovementRange
    {
        get => _model.MovementRange;
        set => SetProperty(_model.MovementRange, value, v => _model.MovementRange = v);
    }

    public int MinEvolutionTableEntry_Max => 2047;
    public int MinEvolutionTableEntry
    {
        get => _model.MinEvolutionTableEntry;
        set => SetProperty(_model.MinEvolutionTableEntry, value, v => _model.MinEvolutionTableEntry = v);
    }

    public int MaxEvolutionTableEntry_Max => 2047;
    public int MaxEvolutionTableEntry
    {
        get => _model.MaxEvolutionTableEntry;
        set => SetProperty(_model.MaxEvolutionTableEntry, value, v => _model.MaxEvolutionTableEntry = v);
    }

    public int NationalPokedexNumber_Max => 1023;
    public int NationalPokedexNumber
    {
        get => _model.NationalPokedexNumber;
        set => SetProperty(_model.NationalPokedexNumber, value, v => _model.NationalPokedexNumber = v);
    }

    public int NameOrderIndex_Max => 255;
    public int NameOrderIndex
    {
        get => _model.NameOrderIndex;
        set => SetProperty(_model.NameOrderIndex, value, v => _model.NameOrderIndex = v);
    }

    public int CatchRate_Max => 255;
    public int CatchRate
    {
        get => _model.CatchRate;
        set => SetProperty(_model.CatchRate, value, v => _model.CatchRate = v);
    }

    public int UnknownAnimationValue_Max => 15;
    public int UnknownAnimationValue
    {
        get => _model.UnknownAnimationValue;
        set => SetProperty(_model.UnknownAnimationValue, value, v => _model.UnknownAnimationValue = v);
    }

    public int BattleIntroSpriteOffset_Max => 7;
    public int BattleIntroSpriteOffset
    {
        get => _model.BattleIntroSpriteOffset;
        set => SetProperty(_model.BattleIntroSpriteOffset, value, v => _model.BattleIntroSpriteOffset = v);
    }

    public int Weight_Max => 7;
    public int Weight
    {
        get => _model.Weight;
        set => SetProperty(_model.Weight, value, v => _model.Weight = v);
    }
}