// This file is automatically generated

#nullable enable

using RanseiLink.Core.Enums;
using RanseiLink.Core.Graphics;
using RanseiLink.Core.Models;
using RanseiLink.Core.Services;

namespace RanseiLink.GuiCore.ViewModels;

public partial class WarriorSkillViewModel : ViewModelBase
{
    private WarriorSkill _model = new(default);
    private WarriorSkillId _id;
    public int Id => (int)_id;


    public string Name
    {
        get => _model.Name;
        set => SetProperty(_model.Name, value, v => _model.Name = v);
    }

    public int Effect1Amount
    {
        get => _model.Effect1Amount;
        set => SetProperty(_model.Effect1Amount, value, v => _model.Effect1Amount = v);
    }

    public WarriorSkillEffectId Effect1
    {
        get => _model.Effect1;
        set => SetProperty(_model.Effect1, value, v => _model.Effect1 = v);
    }

    public WarriorSkillEffectId Effect2
    {
        get => _model.Effect2;
        set => SetProperty(_model.Effect2, value, v => _model.Effect2 = v);
    }

    public int Effect2Amount
    {
        get => _model.Effect2Amount;
        set => SetProperty(_model.Effect2Amount, value, v => _model.Effect2Amount = v);
    }

    public WarriorSkillEffectId Effect3
    {
        get => _model.Effect3;
        set => SetProperty(_model.Effect3, value, v => _model.Effect3 = v);
    }

    public int Duration
    {
        get => _model.Duration;
        set => SetProperty(_model.Duration, value, v => _model.Duration = v);
    }

    public int Effect3Amount
    {
        get => _model.Effect3Amount;
        set => SetProperty(_model.Effect3Amount, value, v => _model.Effect3Amount = v);
    }

    public WarriorSkillTargetId Target
    {
        get => _model.Target;
        set => SetProperty(_model.Target, value, v => _model.Target = v);
    }

    public MoveAnimationId Animation
    {
        get => _model.Animation;
        set => SetProperty(_model.Animation, value, v => _model.Animation = v);
    }

    public string Description
    {
        get => _msgService.GetMsgOfType(MsgShortcut.WarriorSkillDescription, Id);
        set => _msgService.SetMsgOfType(MsgShortcut.WarriorSkillDescription, Id, value);
    }
}